### ISSUE TITLE
Update text for hybrid heat pump

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1001]
@AlexanderWirtz please review and improve the text for hybrid heat pumps for both space heating and hot water.

![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/11682487/91910600-9e65-11e5-952e-3ece120a6416.png)

**Comment by AlexanderWirtz** [comment]
@RobTerwel Please review what I wrote (in English) for space heating and hot water. Help me to make it shorter please.

**Comment by RobTerwel** [comment]
@AlexanderWirtz I have edited the texts and shortened them. I rewrote some parts for space heating and removed some lines I thought were not essential to the audience. I made a copy of your initial writings, in case we would want to revert changes.

I reduced it to about 80% of its original length, but I could shorten it more if need be. I think there is still some overlap between the first and the second paragraph (about the role of the gas-fired heater), but not much.

**Comment by AlexanderWirtz** [comment]
I have settled on the text below. Will translate to Dutchness.

>>This heater is a combination of an electric heat pump that draws its heat from the outside air and an efficient conventional gas-fired boiler. The gas-fired part takes over all of the heating of the building on cold winter days, when heat demand peaks. Because of this clever trick, the heat pump has less impact on the electricity grid than an all-electric heat pump does. Smart use of hybrid heat pumps may therefore avoid the need to reinforce local power grids. Essentially, the hybrid heat pump offers a way to strongly reduce natural gas demand for heating, while buying time for grid management companies to reinforce grids.
<br/><br/>
Heat pumps move heat from one place to another. Refrigerators use heat pumps, for example, but buildings can use them for heating and cooling too. For optimal results with <em>most</em> types of heat pump, installation of under-floor and wall heating instead of radiators is often required, as well as good levels of insulation. The <em>hybrid</em> heat pump is an exception, because of its gas-fired heater as a fall-back option. Hybrid heat pumps can intelligently use whichever part (heat pump or gas-fired heater) is the most efficient or cost-effective given the weather conditions and insulation level. Houses with limited insulation will rely on the gas-fired part more, better insulated ones will make more use of the heat pump.

**Comment by RobTerwel** [comment]
:+1:

**Comment by AlexanderWirtz** [comment]
Changed my mind:

>>This heater is a combination of an electric heat pump that draws its heat from the outside air and an efficient conventional gas-fired boiler. Essentially, the hybrid heat pump offers a way to strongly reduce natural gas demand for heating, while buying time for grid management companies to reinforce grids. 
<br/><br/>
This works as follows:<br/>
The gas-fired part takes over all of the heating of the building on cold winter days, when heat demand peaks. Because of this clever trick, the heat pump has less impact on the electricity grid than an all-electric heat pump does. Smart use of hybrid heat pumps may therefore avoid the need to reinforce local power grids. 
<br/><br/>
Heat pumps move heat from one place to another. Refrigerators use heat pumps, for example, but buildings can use them for heating and cooling too. For optimal results with <em>most</em> types of heat pump, installation of under-floor and wall heating instead of radiators is often required, as well as good levels of insulation. The <em>hybrid</em> heat pump is an exception, because of its gas-fired heater as a fall-back option. Hybrid heat pumps can intelligently use whichever part (heat pump or gas-fired heater) is the most efficient or cost-effective given the weather conditions and insulation level. Houses with limited insulation will rely on the gas-fired part more, better insulated ones will make more use of the heat pump.

**Comment by AlexanderWirtz** [comment]
Hot water:

>>This heater is a combination of an electric heat pump that draws its heat from the outside air and an efficient conventional gas-fired boiler. Essentially, the hybrid heat pump offers a way to reduce natural gas demand for hot water, while buying time for grid management companies to reinforce grids. 
<br/><br/>
This works as follows:<br/>
When heat demand peaks, the gas-fired part takes over some of the heating. Because of this clever trick, the heat pump has less impact on the electricity grid than an all-electric heat pump does. Smart use of hybrid heat pumps may therefore avoid the need to reinforce local power grids. For more information see the write-up in the <a href="/scenario/demand/households/space-heating" >space heating section</a>. 
<br/><br/>
Since hot water demand qualifies as high instant heat demand, the use of hybrid heat pumps for hot water generation will rely on the gas-fired part of the system more than using it for space heating.

**Comment by AlexanderWirtz** [comment]
Nederlands ruimteverwarming:
>>Deze verwarmingsoptie is een combinatie van een elektrische warmtepomp met een gasgestookte HR-ketel. Een hybride warmtepomp maakt het mogelijk om snel veel gas voor verwarming te besparen en geeft netbeheerders bovendien meer tijd om stroomnetten te verzwaren.
<br/><br/>
Het werkt zo:<br/>
De gasketel verwarmt het huis op koude dagen, als de warmtevraag het hoogst is. Deze slimme truc zorgt ervoor dat een hybride warmtepomp het stroomnet minder belast dan een elektrische warmtepomp alleen. Door slim gebruik te maken van zulke hybride warmtepompen kan de noodzaak om stroomnetten te verzwaren vermeden worden. 
<br/><br/>
Warmtepompen verplaatsen warmte van de ene plek naar de andere. Koelkasten gebruiken bijvoorbeeld warmtepompen, maar huizen kunnen dat ook doen voor verwarming of koelen. Dit werkt het eigenlijk alleen als gebouwen goed geïsoleerd zijn en als ze vloer- en muurverwarming hebben in plaats van radiatoren. Hybride warmtepompen zijn een uitzondering op deze regel doordat de gasketel ingezet kan worden. Ze kunnen slim kiezen welk deel (de warmtepomp of de gasketel) het meest efficiënt of kosteneffectief is om aan te zetten, afhankelijk van het weer en hoe goed een huis geïsoleerd is. Minder geïsoleerde huizen zullen de gasketel vaker nodig hebben, beter geïsoleerde huizen gebruiken vooral de warmtepomp.  

Nederlands warm water:
>>Deze verwarmingsoptie is een combinatie van een elektrische warmtepomp met een gasgestookte HR-ketel. Een hybride warmtepomp maakt het mogelijk om snel gas voor warm water te besparen en geeft netbeheerders bovendien meer tijd om stroomnetten te verzwaren.
<br/><br/>
Het werkt zo:<br/>
De gasketel maakt een deel van de warmte als de warmtevraag het hoogst is. Deze slimme truc zorgt ervoor dat een hybride warmtepomp het stroomnet minder belast dan een elektrische warmtepomp alleen. Door slim gebruik te maken van zulke hybride warmtepompen kan de noodzaak om stroomnetten te verzwaren vermeden worden. Meer informatie vind je in het gedeelte over
<a href="/scenario/demand/households/space-heating" >ruimteverwarming</a>. 
<br/><br/>
Omdat warm water een hoge instantane warmtevraag geeft, zullen hybride warmtepompen om warm water te maken meer gebruik maken van de gasketel dan wanneer ze gebruikt worden voor ruimteverwarming.
