### ISSUE TITLE
Shouldn't energy CHPs be part of the heat production group?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1075]
In a NL 2013 scenario with MO off and many coal energy CHPs, I observe no changes in the heat and cold production chart:

![screen shot 2016-02-10 at 10 01 32](https://cloud.githubusercontent.com/assets/14106387/12942779/92b56f90-cfdd-11e5-8d6e-45dfb95afb4d.png)

A quick inspection of the nodes in ETSource informed me **all** energy CHPs are not included in the `heat_production` group, while industry CHPs for example are. Is there maybe a reason for this, @jorisberkhout ?

If they should appear there, you can assign me back and I'll take care of it.

**Comment by ChaelKruip** [comment]
Well spotted @RobTerwel!

**Comment by jorisberkhout** [comment]
> Well spotted @RobTerwel!

Should we take action, @ChaelKruip ? And if so, which action?

**Comment by ChaelKruip** [comment]
> Should we take action, @ChaelKruip ? And if so, which action?

Good question :laughing: 
I would like to add these CHPs to the `heat_production` group but I think we should talk to @AlexanderWirtz first. I am not sure if we would introduce double counting of the energy used by these plants (in the energy use dashboard item etc.) if we add them to the heat_production` group because they are also part of the `electricity_production` group.

**Comment by jorisberkhout** [comment]
> I would like to add these CHPs to the heat_production group but I think we should talk to @AlexanderWirtz first. I am not sure if we would introduce double counting of the energy used by these plants (in the energy use dashboard item etc.) if we add them to the heat_productiongroup because they are also part of theelectricity_production` group.

Sounds like we need to discuss this in a bit more detail. Let's do that after the deploy.

**Comment by jorisberkhout** [comment]
Assigning our CHP-modelling-expert, @ChaelKruip .

**Comment by TessColijn** [comment]
@ChaelKruip I have added the CHPs to the 'heat_production'. On my local model i obtain feedback in the Heat and Cold Production table as desired. 

I looked at the dashboard and some other charts and tables and checked for changes but couldn't find any. I will send you a pull request so that we can close this issue.

**Comment by ChaelKruip** [comment]
> I will send you a pull request so that we can close this issue.

👍 

If you include the text "Fixes issue https://github.com/quintel/etsource/issues/1075" in the description part of the pull request, this issue will automagically be closed! Cool huh?
