### ISSUE TITLE
Waste CHP slider has higher start_value than max_value

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1076]
![screen shot 2016-02-10 at 10 17 49](https://cloud.githubusercontent.com/assets/14106387/12943152/92931c36-cfdf-11e5-9b1e-14b9316d1500.png)

The <a href="https://github.com/quintel/etsource/blob/master/inputs/supply/number_of/number_of_energy_chp_supercritical_waste_mix.ad#L7-L10"a>waste CHP input statement<a/>  contains the following values for  a NL 2013 dataset:

``
start_value = present:V(energy_chp_supercritical_waste_mix,number_of_units) = 12.3
``

But its `max_value` is define in two ways:

``
max_value = 300
``
``
max_value_gql = present:MAX(1.0,DIVIDE( DIVIDE( Q(total_electricity_produced), V(energy_chp_supercritical_waste_mix,maximum_yearly_electricity_production_per_unit) ), 20 ))
``

And the latter value evaluates to 10.7 . Therefore the `start_value` of the input is higher than its max value.

@jorisberkhout , would you know a) why we use two `max_values` and b) why the `max_value_gql` looks this way? 

Re-assign at will.

**Comment by jorisberkhout** [comment]
> @jorisberkhout , would you know a) why we use two max_values and b) why the max_value_gql looks this way?

Do you know the answer to this, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> why we use two max_values

This is an ancient artefact of a time when max-values were hard-coded. The hard-coded value is used as a fall-back for when the GQL-statement would not work. Because it is highly unlikely that the ETM would function but the GQL would not work I think this qualifies for clean-up.

> why the max_value_gql looks this way?

This is an attempt to have slider caps that scale dynamically with the total countries energy production. So, in human language the max-gquery says: "This CHP-type should be able to make 5% of the total electricity production of the country, whatever that is in 'units'".

>  Therefore the start_value of the input is higher than its max value.

In the CHP analysis, @AlexanderWirtz does some black magic on the energy balance to derive initial number of units for each CHP. The initial number of CHPs is therefore de-coupled from the previous 5% estimate. Apparently, these CHPs make more than 5% of the total electricity. So, perhaps we should not divide by 20 but by 10 or so...

**Comment by RobTerwel** [comment]
@ChaelKruip , thanks for explaining! I guess that indeed we could

> divide [...] by 10 or so

although that doesn't solve the latent, more fundamental problem, since we at this point have no check whether there are exceptions to these assumptions. Time to expand our turk? :wink:

**Comment by ChaelKruip** [comment]
> Time to expand our turk?

I think there is a more logical place for this:

[this page](http://beta.et-engine.com/data/latest/inputs) shows all values, a consistency check could be implemented quite easily. This would only be useful if the user gets a warning that a check fails when importing a commit though.

Including @antw

**Comment by ChaelKruip** [comment]
For now I suggest to divide by 10. I'll pick that up.

**Comment by jorisberkhout** [comment]
Closed by #1078 .
