### ISSUE TITLE
Experience and investigate what you currently need to do to accomplish a scaled dataset

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1181]
@antw could you maybe show a simple example of how to create a local dataset; how this is currently done. I've learned about the `user_values` (`*_both`, `*_present`) hack in a scenario in ETEngine. But what does that boil down to? Could you explain it to me - or point out where I can find the way it currently technically works.

**Comment by antw** [comment]
> See title

I'm not sure what the title means. 😆  Can you clarify?

**Comment by grdw** [comment]
> Can you clarify?

Was just working on it 👍 

> @antw could you maybe show a simple example of how to create a local dataset; how this is currently done. I've learned about the user_values (*_both, *_present) hack in a scenario in ETEngine. But what does that boil down to? Could you explain it to me - or point out where I can find the way it currently technically works.

**Comment by antw** [comment]
> I've learned about the user_values (*_both, *_present) hack in a scenario in ETEngine.

It sounds like you mean the Ameland and Groningen scenarios which have been created by taking scaled down NL scenarios and are then tweaked using `_present` inputs?

ETEngine has two graphs: one for the present year (normally 2013) and one for the future year. Inputs normally affect only `future`, with the `present` being mostly immutable. Since scaling down NL to the size of Ameland or Groningen didn't accurately represent those regions (too much or too little industry, for example) Rob, Alexander, and others created [inputs which instead adjust the present-year graph](https://github.com/quintel/etsource/tree/master/inputs/adjust_scaling). Note that the inputs in that directory [all have `update_period = present`](https://github.com/quintel/etsource/blob/a8954a7bd8c81962f0a7b850844419d26601a066/inputs/adjust_scaling/transport/transport_car_using_electricity_share_present.ad#L22) instead of [the normal `update_period = future`](https://github.com/quintel/etsource/blob/a8954a7bd8c81962f0a7b850844419d26601a066/inputs/demand/transport/transport_car/transport_car_using_electricity_share.ad).

However, there's nothing specific in ETEngine to make those scenarios work; it's all done through those inputs.

Dennis, Alexander, Chael, Joris, and I discussed a more robust replacement to this, which will use Atlas and Refinery to create first-class datasets for those regions (instead of the current hacky solution which needs `_present` inputs), but I haven't had a chance to get around to that yet.

Did something motivate this question? I might be able can give a more specific answer if I know what you want to achieve.

**Comment by grdw** [comment]
> However, there's nothing specific in ETEngine to make those scenarios work; it's all done through those inputs.

A few questions still: how are those input statements linked to a certain scenario? Is that what you'd put in the `user_values` column of a certain scenario?

If so: to put this into my own words and understanding. You have a scenario in et-engine. A scenario has a `user_values` column. In that `user_values` column you specify for example: `[number_of_buildings_present](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/number_of_buildings_present.ad) = x`. That will set the present value in the graph for `number_of_buildings` in ETEngine (how does that work exactly?). Also how is the present graph initialized? (Is that done through refinery? and how exactly? Is that with the `etsource/datasets/nl.ad` files etc.?) I don't really understand what connects it all yet or what the relations are. To me it are all loose files.

> but I haven't had a chance to get around to that yet.

I think the idea is that Peter and I are going to be working on this, if I'm correct? @ChaelKruip  @dennisschoenmakers

**Comment by dennisschoenmakers** [comment]
> I think the idea is that Peter and I are going to be working on this, if I'm correct? @ChaelKruip @dennisschoenmakers

Absolutely correct. I do expect the two of you to draw up 'a plan' first how you want to deal with this. Of course you can experiment in a separate branch.

**Comment by antw** [comment]
> how are those input statements linked to a certain scenario? [...]  That will set the present value in the graph (how does that work exactly?). Also how is the present graph initialized? (Is that done through refinery? and how exactly? Is that with the etsource/datasets/nl.ad files etc.?) I don't really understand what connects it all yet or what the relations are.

Those are some quite wide-ranging questions. :grinning:

![64873419](https://cloud.githubusercontent.com/assets/4383/20009172/624c10e8-a29b-11e6-9c86-df46010276dc.jpg)

---

I'm having a hard time satisfactorily answering these questions, because they cover almost everything from Refinery and Atlas to ETEngine. That's probably 75% of our backend. Just about the only thing *not* covered by those questions is ETEngine GQL/queries. :grinning:

I know we *should* have better documentation for this stuff (sorry), but if I try to describe everything it's going to be an overwhelming number of concepts at once: links, edges, converters, final demand, useful demand, primary energy, slots, carriers, efficiency, shares, energy balances, and so on... I'll try to keep it simple.

### ETSource

* ETSource describes the structure of the graph through [Node](https://github.com/quintel/etsource/tree/master/nodes) and [Edge](https://github.com/quintel/etsource/tree/master/edges) files. You can see [a visual representation of the graph on ETEngine](https://beta-engine.energytransitionmodel.com/data/latest/layout). The structure is the same for all regions.

* The *data* in a dataset or graph is region-specific:

  * This data may be global to the region, in which case it lives in the AD file – [such as the number of households](https://github.com/quintel/etsource/blob/a8954a7bd8c81962f0a7b850844419d26601a066/datasets/nl/nl.ad#L62-L63).

  * It may instead describe something more specific, such as "[demand for natural gas in households](https://github.com/quintel/etsource/blob/a8954a7bd8c81962f0a7b850844419d26601a066/nodes/households/households_final_demand_network_gas.final_demand.ad#L6-L8)", in which case this is specified as a query in a Node or Edge file. These queries map data from CSV files in ETSource to nodes and edges in Atlas. The CSVs come from Excel files in [ETDataset](https://github.com/quintel/etdataset); researchers and modellers live there and we don't need to think much about it.

### Atlas & Refinery

Atlas and Refinery are **offline** tools for taking data from ETSource and producing a present-year graph which can be used in ETEngine.

```
      Compile time /
<---- ahead-of-time ---->   <- Runtime ->

ETSource -----> Atlas -----> ETEngine
                  ^     |
                  |     |
            Refinery <--'
```

[Atlas' `Runner` class](https://github.com/quintel/atlas/blob/master/lib/atlas/runner.rb) is responsible for this process. For the dataset being calculated, it:

1. [Maps demand and shares](https://github.com/quintel/atlas/blob/master/lib/atlas/runner.rb#L41-L47) from the CSV files to nodes and edges, to produce a sparse graph ([here's an example for just the agriculture sector](https://cloud.githubusercontent.com/assets/4383/20014473/088633e0-a2af-11e6-880d-7d12a1acd4a2.png)).

2. [Applies some transformations to the graph](https://github.com/quintel/atlas/blob/master/lib/atlas/runner.rb#L49-L53) prior to calculation (called "catalysts"; I don't know what I was thinking when I chose that name), and

3. Sends the lot to [Refinery](https://github.com/quintel/atlas/blob/master/lib/atlas/runner.rb#L21-L33) which does the actual calculation. Refinery gives you back the [finished (present) graph](https://cloud.githubusercontent.com/assets/4383/20014589/82a47132-a2af-11e6-9985-53850da23564.png).

Wouldn't it be interesting if there were a catalyst called `ScaleDemandsToLocalRegion`? *(cough)*

I imagine the solution to this problem is 75% Atlas and 25% ETEngine. You probably don't need to do anything with inputs, and Refinery can be treated as an opaque box: [data goes in, results come out](https://youtu.be/wb3AFMe2OQY?t=1m51s), it shouldn't need any changes (it's basically a finished project unless we one day add a new type of edge or an all-new concept to ETEngine's graph).

If you go to your Atlas clone and run `rake debug DATASET=nl`, everything I have described so far will happen for the NL dataset. It will be somewhat slow due to the debug task creating diagrams for each sector.

### ETEngine

ETEngine does a bit more work before it can use the present year graph produced by Atlas. It:

1. [Has Atlas figure out what data is needed by ETEngine](https://github.com/quintel/atlas/blob/master/lib/atlas/exporter.rb).

2. [Dumps that data to a MessagePack file](https://github.com/quintel/etengine/blob/221fbf0eab973f73adbb8b5ddc91928ad09c99a7/app/models/etsource/atlas_loader.rb#L61-L65).

If you are running in development and your config.yml has `etsource_lazy_load_dataset: true`, [ETEngine will perform this task lazily](https://github.com/quintel/etengine/blob/221fbf0eab973f73adbb8b5ddc91928ad09c99a7/app/models/etsource/atlas_loader.rb#L145-L175) the first time you try to use a dataset. In production – with that option set to `false` – [all datasets are calculated during the deploy](https://github.com/quintel/etengine/blob/221fbf0eab973f73adbb8b5ddc91928ad09c99a7/app/models/etsource/atlas_loader.rb#L121-L143). You can see this in action by running `rake deploy:calculate_datasets`.


```
ls -l /var/www/etengine/current/tmp/atlas

total 4480
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 be.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 br.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 de.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 es.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 eu.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 fr.pack
-rw-rw-r-- 1 ubuntu ubuntu 454940 Nov  3 17:25 nl2012.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 nl.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 pl.pack
-rw-rw-r-- 1 ubuntu ubuntu 454964 Nov  3 17:25 uk.pack
```

*(When developing ETEngine and you aren't making any changes to ETSource, you may prefer to run with that option as `false` and calculate the datasets with the Rake task. ETEngine is **incredibly** slow to start and reload, and having the datasets pre-calculated can shave off a second or two).*

Everything described so far is offline, ahead-of-time. This stuff does **not** take place every time you make a request to ETEngine.

When you send a request to ETEngine, it makes two copies of the present year dataset (using DeepClone), uses one for the present year graph and one for the future year graph. Inputs are applied with the `user_values`, the graphs are calculated, and queries are run. This is *likely* not relevant to this task; I can describe this in more detail if necessary.

I still think I'm only scratching the surface, particularly on the ETEngine side of things, but hopefully this is enough to get you started with Atlas.

**Comment by ploh** [comment]
@antw 

> Applies some transformations to the graph prior to calculation (called "catalysts"; I don't know what I was thinking when I chose that name), and

What transformations are those?

>  Inputs are applied with the user_values, the graphs are calculated, and queries are run. This is likely not relevant to this task; I can describe this in more detail if necessary.

How are the inputs applied? Especially, if an input changes a demand for one node, that will corrupt the consistency of the graph. So how is this change then propagated through the graph?

**Comment by antw** [comment]
> What transformations are those?

You can [find them here](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/runner.rb#L49-L53) as part of Atlas' runner. I don't think this is relevant to local datasets as it is just setup code for Refinery.

> How are the inputs applied? Especially, if an input changes a demand for one node, that will corrupt the consistency of the graph. So how is this change then propagated through the graph?

ETEngine does not use *all* of the demands from the Atlas+Refinery graph; only some (those which belong to the "preset_demand" group). This is because we get data from third-parties which describe demands in the middle of the graph, but ETEngine needs to know the demands of the left-most nodes in the graph.

Let's say you have three nodes like this, with the left-most one in the "preset_demand" group:

```
+-------+      +---------+      +---------+
| A (2) |  <-  | B (nil) |  <-  | C (nil) |
+-------+      +---------+      +---------+
```

This would be the default graph, assuming that no changes are made by the visitor. Perhaps now you move a slider which sets A=4. The **ETEngine** graph prior to being calculated looks like:

```
+-------+      +---------+      +---------+
| A (4) |  <-  | B (nil) |  <-  | C (nil) |
+-------+      +---------+      +---------+
   ^
   | An input sets A=4
```

... which after calculation now looks like:

```
+-------+      +-------+      +-------+
| A (4) |  <-  | B (4) |  <-  | C (4) |
+-------+      +-------+      +-------+
```

**Comment by ploh** [comment]
> This is because we get data from third-parties which describe demands in the middle of the graph, but ETEngine needs to know the demands of the left-most nodes in the graph.

So the demands outside of the "preset_demand" group are not read in from the atlas+refinery result but computed again by ETEngine?
And is it somehow assured that the "preset_demand" group demands are sufficient to compute the whole graph?

> ... which after calculation now looks like:

But what happens in the case of https://github.com/quintel/etengine/issues/883#issuecomment-262459951

Are the shares kept equal or how else does ETEngine know how to propagate the change through the graph?

Also, what happens when a user value gets executed that uses e.g. https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_cooker_network_gas_share_present.ad
How does this propagate through the graph?

**Comment by antw** [comment]
> So the demands outside of the "preset_demand" group are not read in from the atlas+refinery result but computed again by ETEngine?

It's the other way around. In ETEngine "preset_demand" nodes *are* read from Atlas+Refinery and the rest of the graph is left blank (ETEngine's calculation will figure them out).

> And is it somehow assured that the "preset_demand" group demands are sufficient to compute the whole graph?

Correct. The preset demands, *plus* the shares and conversions computed by Refinery are sufficient for ETEngine to calculate the graph.

> Are the shares kept equal or how else does ETEngine know how to propagate the change through the graph?

Shares of edges are not changed. Let's say the default looks like this:

```
               +--------+
        75% /  | B1 (?) |
+-------+  /   +--------+
| A (4) |
+-------+  \   +--------+
        25% \  | B2 (?) |
               +--------+
```

ETEngine will calculate that B1 has demand of 3 and B2 will have demand of 1.

```
               +--------+
        75% /  | B1 (3) |
+-------+  /   +--------+
| A (4) |
+-------+  \   +--------+
        25% \  | B2 (1) |
               +--------+
```

This says that A has a demand of 4, that 75% of its energy comes from B1 and 25% comes from B2.

If a slider instead sets A=2, then ETEngine will calculate B1=1.5 and B2=0.5.

```
               +----------+
        75% /  | B1 (1.5) |
+-------+  /   +----------+
| A (2) |
+-------+  \   +----------+
        25% \  | B2 (0.5) |
               +----------+
```

Shares *can* be overridden in inputs, but this is done explicitly.

> Also, what happens when a user value gets executed that uses e.g. [...] How does this propagate through the graph?

In this case the input sets a new share value:

```
               +--------+
        50% /  | B1 (2) |
+-------+  /   +--------+
| A (4) |
+-------+  \   +--------+
        50% \  | B2 (2) |
               +--------+
```
