### ISSUE TITLE
Initializer inputs transport_car_shares in local dataset 

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1236]
When using the initializer inputs  for car shares (running etengine locally), namely:

- init.transport_car_using_compressed_natural_gas_share = 0.0959161346476145
- init.transport_car_using_diesel_mix_share = 23.526528710922
- init.transport_car_using_electricity_share = 0.139468378767934
- init.transport_car_using_gasoline_mix_share = 72.0901065653269
- init.transport_car_using_hydrogen_share = 0
- init.transport_car_using_lpg_share = 4.14798021033561, 

an error occurs:

SystemStackError - stack level too deep:
  actionpack (4.1.5) lib/action_dispatch/middleware/reloader.rb:79:in `'

This probably has to do with issue #1223 Mistakes in transport_car carrier share inputs, 

but it is not yet fixed in PR #1235 car-input-fix.

**Comment by antw** [comment]
> This probably has to do with issue #1223 Mistakes in transport_car carrier share inputs,

I think you're right. The `transport_car` inputs work fine with the changes I made on the inputs-cleanup branch (#1237) which has just been merged. You should be able to get these changes on your "drenthe" branch by running the following in your ETSource directory:

* `git fetch` – gets the latest changes from GitHub without doing anything to your local copy
* `git rebase origin/master` – will merge your changes with those from "master" (including the fixes to the transport inputs).
* `git push -f origin drenthe` – will push the changes to GitHub. `-f` is not normally required, but will be this time since you just ran `git rebase` and your local copy will conflict with the one on GitHub.

You may now also have to run `bundle` to update some ETSource dependencies; this will mean that if you run the scaling script again, the time curve files will be created correctly.
