### ISSUE TITLE
Network cost calculation very different between LIVE and BETA

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1281]
After the implementation of the dynamic demand curve, the network costs are very different between [BETA](https://beta-pro.energytransitionmodel.com/scenarios/679665):
![image](https://cloud.githubusercontent.com/assets/1303760/26633598/3667d4c2-4614-11e7-88d1-fb6b26eafbe1.png)

and [LIVE](https://pro.energytransitionmodel.com/scenarios/326244)
![image](https://cloud.githubusercontent.com/assets/1303760/26633602/397dbfb4-4614-11e7-9853-ac49c23de343.png)

Almost a factor 30(!) for a scenario with heat pumps and EV and moderate insulation.

**Comment by ChaelKruip** [comment]
Possible reasons for the discrepancies:
* peak demand are lower because simult constants are no longer used to boost the peak load
* some bug fixes I did in the GQueries when adding the dynamic peak to them
* ...?

**Comment by antw** [comment]
@ChaelKruip and I have investigated:

1. The dynamic curves spread the demand/load more evenly. If the curves used have very large peaks the investment costs rise significantly:

    **Hot water and space heating satisfied in one hour per-day with a heat pump:**

    <img width="609" alt="screen shot 2017-06-01 at 09 54 50" src="https://cloud.githubusercontent.com/assets/4383/26672530/67f74e4e-46b1-11e7-8e38-72b10d31c8f0.png">

    **Hot water and space heating satisfied in one hour per-day with a resistive electric heater:**

    <img width="620" alt="screen shot 2017-06-01 at 09 56 12" src="https://cloud.githubusercontent.com/assets/4383/26672569/85b045b2-46b1-11e7-990f-e1d4865f531d.png">

2. The peaks in the dynamic profiles are often not coincident, whereas the previous approach assumes that all technologies peaked simultaneously. For example, the use of hot water peaks a couple of hours before charging EVs:

    <img width="622" alt="screen shot 2017-05-31 at 19 38 36" src="https://cloud.githubusercontent.com/assets/4383/26672681/ee1718d8-46b1-11e7-8cef-68c83e72f007.png">

3. In some cases, heat pumps used a very high `simult` constant – likely to simulate the efficiency of the appliance depending on air temperature. The dynamic curves don't have this, and the result might be that the peaks for that technologies are lower than expected at some times of the year. We might be able to improve this in the future by accounting for air temperature.

**Comment by ChaelKruip** [comment]
To give another few numerical examples of what @antw has shown graphically I give 
the effective peaks of EV, air-heat pumps for hot water and space heating between LIVE and BETA: 

|tech|LIVE [GW]|BETA [GW]|
|---|---|---|
|EV|29|6|
|HP-HW|25|1|
|HP-SH|16|3|

The non-linear relation between peak and network cost blows up these differences even more.

@jorisberkhout @AlexanderWirtz @antw we need to decide soon what we want to do with this. I see three major options:
* Leave the new implementation online and try to find time to fix it ASAP
* Take the network calculation off-line until we have fixed it
* Roll back the recent improvements and keep the old version online until we have a better version

In all cases we might want to put a very big "Indicative" label on everything that has to do with network costs.

**Comment by antw** [comment]
> If the curves used have very large peaks, the investment costs rise significantly:

I created another example in an attempt to get closer to the old behaviour of network costs. I created a profile with two peaks per day – one in the day-time and one in the evening. I used this same curve for space heating, hot water, and EV charging (the previous screenshots used the custom profile only for hot water).

Here's the result:

![screen shot 2017-06-01 at 12 56 20](https://cloud.githubusercontent.com/assets/4383/26678791/13156212-46ca-11e7-8822-24df64e602de.png)

Total costs are still 50% lower than "live", but the difference is no longer quite so extreme.

This isn't a very fair comparison, since it results in a relatively constant peak load throughout the year, whereas the old approach had quite large differences between summer and winter due to the `simult` constants of heat pumps (some as low as 0.0 in summer, others as high as 3.7 in winter).

So... I did something silly and used a weighted average of the old `simult` constants for heating, hot water, and EVs, an adjusted the Merit peak loads:

| Scenario | Production | Local |
| --: | -- | -- |
| 100% heat pumps | ![aa1-hp-prod](https://cloud.githubusercontent.com/assets/4383/26680126/060a799e-46d0-11e7-9681-19c687b6c4f6.png) | ![aa2-hp-head](https://cloud.githubusercontent.com/assets/4383/26681331/c54af316-46d4-11e7-9a79-71c6373442fa.png) |
| 100% resistive heaters | ![aa3-resistive-prod](https://cloud.githubusercontent.com/assets/4383/26680128/060c87f2-46d0-11e7-9665-88e53ade7765.png) | ![aa4-resistive-head](https://cloud.githubusercontent.com/assets/4383/26680129/060d1fa0-46d0-11e7-93dc-adc54675142c.png) |

The cost when using heat pumps doesn't change much, but costs with resistive heaters end up *higher* than the old implementation (`simult_sd = 0.0`, `simult_we=3.12`).

This leads me to the conclusion that costs are different because:

1. Load is spread more evenly throughout the day with dynamic curves.
2. `simult` constants have a significant effect on the cost calculation and tends to amplify peak loads in winter. (Also: why does the electric space heater have `simult_we=3.12`)?

*That is not to say the new costs are correct*, but this is why they're so much lower.

> * Leave the new implementation online and try to find time to fix it ASAP
> * Take the network calculation off-line until we have fixed it

Do you know what a fix might be? I can't speak to the costs, but I my feeling is that the new peak *loads* are correct.

**Comment by ChaelKruip** [comment]
> That is not to say the new costs are correct, but this is why they're so much lower.

Thanks for the excellent analysis @antw! I have come to another realisation:

The old method *does not take insulation or heat demand into account*. It is a worst-worst-case calculation which just adds up all capacity without taking the actual heating demand into account. 

In that sense, our new implementation is much more realistic. If we correct for the simult-factors, it is perfectly possible to reach the high costs of the old method by simply not insulating houses.

> Do you know what a fix might be? I can't speak to the costs, but I my feeling is that the new peak loads are correct.

I think for now there is nothing to fix. One improvement would be to make COP temperature dependent (and therefore time dependent). I have some further more general ideas for improving the network calculations but they are not fallout of the dynamic demand curve.

For now I think I'll remove the 'bug' and 'priority' labels.

**Comment by ChaelKruip** [comment]
Closing as this is on production now and we know the reasons.
