### ISSUE TITLE
Number of cars is defined twice in current local datasets

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1285]
In the .ad file of a local datasets currently number_of_cars is defined twice

For example for Noorderplantsoenbuurt:
`- init.number_of_cars = 930`
`- number_of_cars = 930.0`

I guess this is because custom number of cars was set in: https://github.com/quintel/etsource/commit/ec4bb52634f6b6849ade064c122b06efe1c25ee1 

I noticed that just the initializer input influences the dataset. Is this indeed the case?

Should we
- Not define `number_of_cars` in future local datasets?
- Remove the line setting `number_of_cars` in the present local datasets? (I think this is unnecessary)?

notifying @ChaelKruip

**Comment by antw** [comment]
> Not define number_of_cars in future local datasets?

It's my hope that we can soon remove the `number_of_cars` attribute entirely, since it is now replaced by `number_of_units` on the `transport_useful_demand_car_kms` node. Local datasets will therefore define [`init.number_of_cars = ...`](https://github.com/quintel/etsource/blob/b7a35886764985f9820f6762c6410a6fd3977e0f/initializer_inputs/number_of/number_of_cars.ad) whenever the automatically-scaled value needs to be customised.

To make this happen we would need to add a CSV file to each dataset storing the number of cars (and trucks, and anything else...). What is the original source of the `number_of_cars` value in full-size datasets? Is it added manually in ETSource, or does it come from an Excel file in ETDataset?

**Comment by ChaelKruip** [comment]
Notifying @jorisberkhout as he can answer these questions best in my estimation

**Comment by jorisberkhout** [comment]
The `number_of_cars` area attribute is set in the `11_area_analysis` in ETDataset. In this analysis the user is prompted for this number, which is directly passed on to the `<area>.ad` and is not used in any way in other analyses.

**Comment by antw** [comment]
> The `number_of_cars` area attribute is set in the 11_area_analysis in ETDataset.

Thanks. :+1:

So if we want to remove the value from the `<area>.ad` and store it in a CSV, what would be the best course of action? Would it be good enough to remove the lines from the Excel analysis and add a new hand-edited CSV to ETSource, or should the value still exist somewhere in ETDataset?

**Comment by marliekeverweij** [comment]
Closing this issue as there are no datasets anymore that are generated with initializer_inputs, right @michieldenhaan ?

BTW: can we remove `initializer_inputs` entirely? https://github.com/quintel/etlocal/issues/126

**Comment by redekok** [comment]
> BTW: can we remove initializer_inputs entirely? quintel/etlocal#126

This is also discussed in https://github.com/quintel/etsource/issues/1972.
