### ISSUE TITLE
Solar roof surface in buildings sector doesn't increase with number of buildings

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1330]
The input number_of_buildings.ad increases demand: 

 `- query = UPDATE(V(buildings_useful_demand_for_appliances,buildings_useful_demand_light,buildings_useful_demand_for_space_heating,buildings_useful_demand_cooling), preset_demand, USER_INPUT())`

but not the roof surface available for solar PV. It think it should, we already do it in the household sector (households_number_of_new_houses.ad and households_number_of_old_houses.ad). 

@AlexanderWirtz @DorinevanderVlies what do you think? Should I make a proposal for a new input? And do you have any idea how many scenario's will be affected (I would assume almost all of them, but the significant impact should be limited to the ones with considerable buildings sector growth).

**Comment by AlexanderWirtz** [comment]
> @AlexanderWirtz @DorinevanderVlies what do you think? Should I make a proposal for a new input? And do you have any idea how many scenario's will be affected (I would assume almost all of them, but the significant impact should be limited to the ones with considerable buildings sector growth).

1. Well spotted!
2. This is a bug not a feature and needs to be fixed: so yes, please propose a fix
3. Agree with you on the impact assessment. Featured scenarios on the front page and Groningen neighborhood and GEA provincial scenario's first come to mind
4. The fix for these affected scenarios would be to keep the solar PV power production in these scenarios constant. It should be possible to work out a database migration which scales back the %-slider in order to counteract the increased roof surface.

**Comment by DorinevanderVlies** [comment]
I agree with @AlexanderWirtz

**Comment by antw** [comment]
> The fix for these affected scenarios (after fixing this issue that is) would be to keep the solar PV power production in these scenarios constant. It should be possible to work out a database migration which scales back the %-slider in order to counteract the increased roof surface.

@nairnamratha has adjusted important presets to keep PV production constant, but personally I'm unconvinced that we should do this for *all* scenarios in the database.

If a visitor set a certain number of buildings and a *percentage* of solar PV, then I think we should respect the choices they made even if it increases the amount of solar *production* in their scenario. They chose that amount of PV after all; they didn't get it previously due to a bug.

---

Including @ChaelKruip

**Comment by nairnamratha** [comment]
Just discussed it with @AlexanderWirtz, he confirmed that in most cases the users have put more thought in to the actual PV production than the slider values themselves, which is why we should keep the PV production constant for all cases even if that requires adjusting the slider values in the scenarios.

**Comment by AlexanderWirtz** [comment]
> he confirmed that in most cases the users have put more thought in to the actual PV production than the slider values themselves

That is just my experience from creating energy scenarios with local actors. Often they have some idea of how many MWp or PJ of solar power they want and just set the slider accordingly. However, this is not universally the case. Of course, it does happen that people set it to a certain percentage. Even in those cases however they tend to take away from the exercise that they can produce a certain amount of solar energy and forget about the slider setting.

**Comment by antw** [comment]
> Even in those cases however they tend to take away from the exercise that they can produce a certain amount of solar energy and forget about the slider setting.

That is helpful to know. Perhaps it therefore makes sense to adjust the sliders with the goal of keeping production constant (or as close as possible).

@nairnamratha do you have a formula for how to adjust the sliders?

---

On a side-note, can I suggest a compromise? Instead of updating *all* scenarios in the database (of which there are 400k on beta), we could limit the update to:

1. Scenarios which a visitor has saved (they want to keep it).
2. Scenarios which were created in the past couple of weeks.

Unsaved scenarios more than a few weeks old are likely abandoned, and updating them is almost certainly pointless (but increases the migration runtime from a minute or two to an hour).

**Comment by nairnamratha** [comment]
> @nairnamratha do you have a formula for how to adjust the sliders?

Here's the method I followed to get the new slider values, please let me know if I haven't explained something clearly: 

1. Growth factor was calculated as (`number_of_buildings`/100)+1)^(end year-start year) (NOTE: the `number_of_buildings` slider denotes a %/y change, i.e. growth in demand, and not an increase in the absolute value of number of buildings)

2. The `buildings_solar_pv_solar_radiation_market_penetration` value is calculated based on this growth factor:
 	= old `buildings_solar_pv_solar_radiation_market_penetration` slider value/ growth factor

To check whether this new market penetration value makes sense, I compared the beta server with my local machine, which shows that the new solar market penetration value calculated using this method keeps the PV production constant. 

> we could limit the update to:
> Scenarios which a visitor has saved (they want to keep it).
> Scenarios which were created in the past couple of weeks.

This makes  sense in my opinion.

**Comment by nairnamratha** [comment]
Updated on beta server.
