### ISSUE TITLE
Do I need to explicitly set the preset demand for energy power converters when updating the number of units when initializing the graph with the new initializer 'methods'?

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1342]
To explain: when setting the number of units of a converter like this:

```ruby
EACH(
  UPDATE(V(energy_power_wind_turbine_offshore), number_of_units, USER_INPUT()),
  UPDATE(L(energy_power_wind_turbine_offshore), preset_demand_by_electricity_production, V(energy_power_wind_turbine_offshore, production_based_on_number_of_units))
)
```

.. there's a second line which updates the energy production by those number of units (I see this happening a lot). As @ChaelKruip showed me, this has to do with the merit order module. When initializing a graph however, the merit order is probably not affecting the energy bit and only setting the number of units would be all there's to it .... I guess. Can you confirm this @antw ?

**Comment by ChaelKruip** [comment]
> As @ChaelKruip showed me, this has to do with the merit order module.

What I tried to say is that if Merit is 'off', the demand of the 'constant' edge needs to be set in order for the graph to be calculable. Is that right @antw?

**Comment by antw** [comment]
> When initializing a graph however, the merit order is probably not affecting the energy bit and only setting the number of units would be all there's to it

I don't think this has anything *specifically* to do with Merit (although it will use the `demand` of the converter), but I might be wrong about that.

These converters produce energy and are calculated from right to left (unlike the rest of the graph) because they have reversed flexible links connecting them with the HV network. The inputs in the ETM allow a user to set the production of these power plants by choosing how many units are installed. 1 unit = 2PJ produced, 2 units = 4PJ produced, etc.

The input achieves this by setting the number of units (which is not a "special" attribute, it's just a number; more on this in a sec) and then sets the actual energy demand in the second line. If you *only* change the number of units, the demand of the converter will not change.

For example, imagine a converter which has a demand of 10PJ and has only 1 unit installed, and is running at 100% capacity to meet that demand. If you now use an input to set "2" units, the demand will still be 10PJ, but each unit must now run at only 50% capacity to meet the same demand. Set number of units to "4" and the capacity used is now 25%, and so on...

**Comment by grdw** [comment]
So each time we update the number of units, the demand should increase to not influence the capacity in a negative way.

One follow up question: while looking at this initializer inputs the `p2h`, `p2g` and `p2p` demands are not altered when updating the number of units. Why is that? Is that because the demand is 0?

**Comment by ChaelKruip** [comment]
>  while looking at this initializer inputs the p2h, p2g and p2p demands are not altered when updating the number of units. Why is that? 

For these nodes, the demand they will have depends on the amount of *excess* electricity the model calculates. This is not know until after Merit has ran.

**Comment by grdw** [comment]
So we have *three ways* of setting `number_of_units`

1. `number_of_units`

This is just setting the `number_of_units` attribute. Only relevant for `p2h`, `p2g`, `p2p`

2. `number_of_units` with `demand`

Updating the `number_of_units` should also set the correct demand. Relevant for `energy_power_*` converters and the likes.

3. `number_of_units` with the correct `share`.

I see this happening in chp's.

**Comment by grdw** [comment]
Including @BerendSmits

**Comment by BerendSmits** [comment]
We're having a bit of a dilemma concerning this issue with the initializer methods.

 As IM is right now, you will need to set both the demand and the number of units, or otherwise it will keep one of those constant and change FLH. That's not ideal, it will require something making a dataset (Excel or ETlocal transformers) to always know the demand per unit. Not impossible, but makes a bit of a mess of the supply analysis (either in excel or etlocal).

The other option would be to teach the initializer methods that a number_of_units goes with a demand update (and vice versa). That might require one or more 'methods' added to our initializer methods. 

What would be your preference in these two options (or can you think of another way to deal with this issue) @ChaelKruip @antw @grdw @DorinevanderVlies ? 

I would say I'm leaning towards keeping it as it is, in line with our 'analysis is done in etlocal, initializers only put stuff into etengine' rule.

**Comment by antw** [comment]
Just so that I can be sure I'm not misunderstanding, the two options are:

1. Have separate initializer methods for `number_of_units` and `demand` and set both attributes separately.
2. Have a single `number_of_units` initializer method which automatically sets demand.

I have no strong opinion one way or the other. I would think that (2) might be complicated by the fact that some converters want demand to change when setting number of units, and others might not.

With that said, I think this is exactly the point of creating prototypes: to try stuff out and see what works, and what doesn't. I find it hard to reason about the myriad ways either approach might affect the analysis or ETEngine.

**Comment by grdw** [comment]
Personally I have a feeling that 1 is the only feasable way of updating the graph. 2 is going to be:

- just setting the number_of_units (in the case of P2H, P2G, .. )
- number_of_units which automatically set a share (in the case of for example argriculture CHP's)
- number_of_units which automatically set a demand

Which - is doable - but not very practical. For instance, which share do you alter for a CHP when updating a number of unit? Are these all output or input shares? It's too flexible.

**Comment by ChaelKruip** [comment]
> Personally I have a feeling that 1 is the only feasable way of updating the graph

I have a preference for this at the moment as well because it keeps the IM's nice and atomic. 

> With that said, I think this is exactly the point of creating prototypes: to try stuff out and see what works, and what doesn't

Agree 100% with that as well.

**Comment by BerendSmits** [comment]
@ChaelKruip @grdw and I discussed this a bit more in person, and decided to go with #1, which means both demand and number of units need to be set. Any link between the two can be standardized in ETlocal, as well as checks we need on them (FLH>8760 for example).

We do need to check whether setting demand and number_of_units works for every node, for some of them the initializer input sets a share (for instance see https://github.com/quintel/etsource/issues/1358)

**Comment by michieldenhaan** [comment]
Closing, suppose this is no longer relevant as the 'new' initializer methods have been superseded by even newer initializer methods
