### ISSUE TITLE
Should folder structure be uniform between etdataset and etsource?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1371]
In practice, it has proven to be desirable to support datasets for the same country for different start-years. The main reasons:

* We can keep scenario's exactly as they are for longer than a year (barring big changes to the graph and calculation methods)
  * We don't have to migrate old scenario's to the new dataset (often using hard-to-explain assumptions about the intentions of the user)
* We can compare the ETM between different years and learn about the accuracy of our model and the data-analysis leading to new datasets

This is currently done with the NL2012 dataset.
Unfortunately, the scripts that are used in preparing dataset do not support automatic exporting of data for the same region and different years and changing the scripts is a pain.

One possible way out of this unfortunate situation is to change the ETSource folder structure to match that of ETDataset making it easier for the VBA scripts to treat all datasets on equal footing. Right @jorisberkhout?

The wanted folder structure would be something like:
```
etsource
└── datasets
    └── nl
        ├── 2012
        ├── 2013
        └── 2015
    └── de
        └── 2013
...
    └── uk
        └── 2013
```

@jorisberkhout @grdw @antw 
* What do you think about this? 
* What would be your estimate of the time needed to change to this situation?
* How would this approach compare to changing the VBA/rake scripts to deal with the current folder structure?

Also see https://github.com/quintel/etsource/issues/1180

**Comment by grdw** [comment]
> What would be your estimate of the time needed to change to this situation?

**ETSource**
ETSource: 0 hours, since [Atlas knows](https://github.com/quintel/atlas/commit/7bb7c3aab23e5a15508feec05430e59d97dc38f4) where datasets are regardless of their folder structure (it looks to the folder where the .ad file is in). Only if the energy balances start changing their layout and structure from year to year, issues might occur in nodes and edges.

**ETEngine/ETModel**
Maybe some features energywise need to become optional in ETEngine or ETModel but I can't tell which (@antw?). And I think it would be practical to make the start year a select box in the front-end of ETModel (So start year == 'analysis year').

> How would this approach compare to changing the VBA/rake scripts to deal with the current folder structure?

Eh, I'm not sure what you are trying to ask, what the impact is to those scripts are or?

**Comment by ChaelKruip** [comment]
> Eh, I'm not sure what you are trying to ask, what the impact is to those scripts or?

As my limited understanding of this topic goes I think the current scripts cannot deal with multiple years for the same dataset. That is why we support the NL2012 dataset as if it is a different country. This requires manual steps that are error prone. 
An alternative to changing the folder structure of ETSource would be to make the scripts smarter so they can deal with the current folder structure on ETSource. Perhaps this is the easier route? I am trying to get a feeling for the effort that would be needed to do this, if it is possible at all...

**Comment by marliekeverweij** [comment]
I do not think we want to add all national datasets with different start years to ETSource, so my answer to the question in the title would be NO. 

But for the Netherlands we have 2015, 2016 and 2017 datasets on ETSource, so we could something like this:
```
etsource
└── datasets
    └── nl
        ├── 2015
        ├── 2016
        └── 2017
```
However, I think it's this issue is too small to pick up if it can only be applied to `nl`. Shall we close it?

**Comment by redekok** [comment]
This afternoon Mart and I discussed that it might be nice for a user to be able to choose the start year for a local dataset as well--since a lot of scenarios are created based on the 2016 year and wouldn't hold anymore after the update to 2017. In this case we might want to have different years for local datasets as well (and a structure like you suggest would be preferable).

**Comment by marliekeverweij** [comment]
I actually think that when we update the municipal/provincial/regional datasets from 2016 -> 2017 that we should remove the 2016 datasets. Otherwise we have to keep on supporting old datasets, for example next year we will then have to support 2016, 2017 ánd 2018 datasets.

I think we should communicate to all users that made a scenario with a 2016 dataset that there scenario will change because the data has been updated. We then have the choice: are we going to migrate the scenarios? I think we can partly do it, but we should not promise that the outcomes will stay the same.

**Comment by ChaelKruip** [comment]
> I actually think that when we update the municipal/provincial/regional datasets from 2016 -> 2017 that we should remove the 2016 datasets. Otherwise we have to keep on supporting old datasets, for example next year we will then have to support 2016, 2017 ánd 2018 datasets.

> I think we should communicate to all users that made a scenario with a 2016 dataset that there scenario will change because the data has been updated. We then have the choice: are we going to migrate the scenarios? I think we can partly do it, but we should not promise that the outcomes will stay the same.

I think this is part of a bigger discussion about what service we want to provide and what level of stability of scenario-outcomes we can guarantee our users. Let's take this discussion to BaseCamp!
