### ISSUE TITLE
Solar thermal production increases when increasing population

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#1440]
The households_water_heater_solar_thermal is linked to households_useful_demand_hot_water, and   households_useful_demand_hot_water is linked to number_of_inhabitants

![screen shot 2017-11-21 at 15 23 11](https://user-images.githubusercontent.com/33415156/33077391-fdeef3b0-cecf-11e7-8646-6566e77d86fb.png)

households_solar_pv_solar_radiation is not changed by the number_of_inhabitants, but by the amount of houses. Isn't it weird that solar thermal production growths with the population? And if this is chosen for a reason, shouldn't this be consistent with solar pv?

**Comment by ChaelKruip** [comment]
> Isn't it weird that solar thermal production growths with the population? 

Yes, but I don't see a quick fix. 
The demand for hot water should scale with population IMO. 
The underlying issue is that solar thermal production is currently defined as a **percentage** of the demand. 

One possible solution would be to have solar thermal heaters produce an absolute amount of hot water similar to P2H, P2G etc. and distribute that among the households that contain a solar thermal heater.
