### ISSUE TITLE
Split up folders datasets of etsource into folders

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1504]
My inner clean-up lady is acting up:

![screen shot 2018-01-04 at 12 37 21](https://user-images.githubusercontent.com/2676542/34561819-13cef74a-f14c-11e7-955c-4b4e57068b19.png)

Can we simply put them in two folders 'National datasets' and 'Local datasets' like:

```
.
├── example
├── local_datasets
│   ├── almere
│   ├── almere_zeewolde
│   ├── antwerpen
│   ├── baarland
│   ├── de_biezen
│   ├── drenthe
│   ├── dronten
│   ├── flevoland
│   ├── friesland
│   ├── gemeente_groningen
│   ├── goes
│   ├── groningen
│   ├── lelystad
│   ├── noorderplantsoen
│   ├── noordoostpolder
│   ├── paddepoel_noord
│   ├── stedendriehoek
│   ├── urk
│   ├── zeeland
│   └── zeewolde
└── national_datasets
    ├── be
    ├── br
    ├── de
    ├── es
    ├── eu
    ├── fr
    ├── nl
    ├── nl2012
    ├── nl2013
    ├── nl2015
    ├── pl
    └── uk

41 directories

```

**Comment by grdw** [comment]
Including @ChaelKruip @antw @jorisberkhout

**Comment by marliekeverweij** [comment]
I think this would be nice to do, since looking for the national datasets costs some time now. I think it will not cost a lot of time to fix it. But the priority is not so high I think :) 

What should happen to fix this?
- Folder should be generated and datasets should be moved on ETSource
- ETLocal export script should be adjusted and direct to right folder
- ETDataset export script should be adjusted and direct to right folder
