### ISSUE TITLE
Speed up the calculation of a dataset

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1629]
This is probably the wrong repo to complain in, but Semaphore is really slow at the moment due to the tremendous amount of datasets that are being added. 

We can disable the `calculate_spec` for Semaphore - but that feels really bad to do. Another route would be to make the calculating of the datasets themselves significantly faster - but I'm not sure what we could do about it in a short amount of time.

**Comment by antw** [comment]
> We can disable the calculate_spec for Semaphore - but that feels really bad to do.

I agree this is not the right solution; CI is exactly where we want the *whole* suite running.

We can upgrade the plan to two boxes so that ETSource isn't waiting on other projects to finish, but the price increase is silly IMO ($29 → $99).

Some builds seem to be waiting for between one and six minutes to start (but most have no wait) and then take 3-4 minutes to run.

(I do agree that the amount of datasets is getting to be a problem, particularly in ETEngine).

**Comment by grdw** [comment]
> (I do agree that the amount of datasets is getting to be a problem, particularly in ETEngine).

Is this problem something that we need to likely pick up in the coming weeks or is it more a matter of months, years?
