### ISSUE TITLE
Solar and wind have (large) negative primary_demand_of_fossil

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1665]
See below:
![monosnap 2018-04-11 09-27-42 1](https://user-images.githubusercontent.com/32056448/38602356-cc9e2628-3d6a-11e8-97b5-e9638063527f.png)

According to the definitions, renewable electricity itself is considered primary, not the input of 'solar radiation' or 'wind'. Hence, intended behaviour is that ``primary_demand_of_fossil = 0`` and ``primary_demand_of_sustainable`` equals the electricity output of the node.

**Comment by antw** [comment]
Seems to be related to https://github.com/quintel/etengine/commit/f9249af988df4fa89d4590a8559ba1eeb066a45f which was meant to allow `primary_demand_of_*` to work on the flexibility nodes.

Weirdly, querying one of the solar nodes in the sandbox says the demand of fossil is zero, even though the converter page thinks otherwise:

```ruby
V(households_solar_pv_solar_radiation, primary_demand_of_fossil)
# => 0.0
```

I'll try to investigate this today.
