### ISSUE TITLE
Interconnector capacity for local datasets uses NL value

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1757]
The interconnector capacity slider for local datasets shows a scaled value (52 MW in screenshot below), but it looks like ETEngine uses the NL value to calculate imports/blackout hours. 
Q(energy_export_electricity_capacity) returns 5850 MW. When changing the slider and hitting reset, ``Q(energy_export_electricity_capacity)`` does return 52 MW.

![energy transition model - your free independent comprehensive fact-based scenario builder httpsbeta-pro energytransiti 2018-06-22 14-59-05 1](https://user-images.githubusercontent.com/32056448/41777842-0c8ae302-762d-11e8-9992-a93df902feb4.png)

**Comment by antw** [comment]
This seems to be because ETSource queries [are run against the parent dataset](https://github.com/quintel/atlas/commit/ec45de4edc5e07be658ebeece115252181f86787#diff-49efccd3d41eb1ad99c7d8ff4fef343cR50), rather than the derived dataset.

Changing the Runner to use the derived dataset seems to be the obvious solution, but this fails due to the lack of some CSV files (such as central_producers.csv). I think it _should_ be using the derived dataset – and not the parent – so I will figure out how to make this change.

**Comment by michieldenhaan** [comment]
Interesting.. 
One other thing @DorinevanderVlies and I noticed is that when increasing electricity demand in a scenario (e.g. switching to electric boilers) the number of blackout hours does not go up. When changing the interconnector capacity slider and hitting reset, the number does go up. So it's not just the flexibility table that shows the wrong number, the blackout hour calculation is wrong as well.

**Comment by antw** [comment]
> When changing the interconnector capacity slider and hitting reset, the number does go up

That seems entirely consistent with the import/export interconnects inheriting the NL value by default (which is of course _unscaled_). Hitting "reset" sets the default value (which _has_ been scaled).

Region: bd_oosterhout

### Default: (no sliders changed)

**Input values:**

```
None
```

**Capacity:**

```ruby
V(energy_interconnector_imported_electricity, "electricity_output_capacity * availability")
# => 5850.0
```

### Set interconnector capacity to 20MW

Input values: 

```yaml
interconnectors_interconnector_capacity: 20.0
```

**Capacity:**

```ruby
V(energy_interconnector_imported_electricity, "electricity_output_capacity * availability")
# => 20.0
```

### Press "reset" next to interconnector capacity slider

**Input values:**

```yaml
interconnectors_interconnector_capacity: 18.694184632399416 # (default)
```

**Capacity:**

```ruby
V(energy_interconnector_imported_electricity, "electricity_output_capacity * availability")
# => 18.694184632399416
```

> So it's not just the flexibility table that shows the wrong number, the blackout hour calculation is wrong as well.

It's rather hard for the blackout hours calculation to be *wrong*, since all it does is count the number of hours where `demand > supply`. Blackout hours being wrong usually means that something else is wrong: in this case the incorrect import/export capacity.

**Comment by antw** [comment]
> When changing the interconnector capacity slider and hitting reset, the number does go up

That seems entirely consistent with the import/export interconnects inheriting the NL value by default (which is of course _unscaled_). Hitting "reset" sets the default value (which _has_ been scaled).

Region: bd_oosterhout

### Default: (no sliders changed)

**Input values:**

```
None
```

**Capacity:**

```ruby
V(energy_interconnector_imported_electricity, "electricity_output_capacity * availability")
# => 5850.0
```

### Set interconnector capacity to 20MW

Input values: 

```yaml
interconnectors_interconnector_capacity: 20.0
```

**Capacity:**

```ruby
V(energy_interconnector_imported_electricity, "electricity_output_capacity * availability")
# => 20.0
```

### Press "reset" next to interconnector capacity slider

**Input values:**

```yaml
interconnectors_interconnector_capacity: 18.694184632399416 # (default)
```

**Capacity:**

```ruby
V(energy_interconnector_imported_electricity, "electricity_output_capacity * availability")
# => 18.694184632399416
```

> So it's not just the flexibility table that shows the wrong number, the blackout hour calculation is wrong as well.

It's rather hard for the blackout hours calculation to be *wrong*, since all it does is count the number of hours where `demand > supply`. Blackout hours being wrong usually means that something else is wrong: in this case the incorrect import/export capacity.

**Comment by michieldenhaan** [comment]
Sorry, sloppy wording. I meant to say that the blackout hour outcome wasn't as expected. Good to hear that it's part of the same problem, thanks for clarifying!
