### ISSUE TITLE
parent_values.csv should be moved

### ISSUE THREAD

**Issue by antw** [quintel/etsource#1773]
Running `rake import` to import a new dataset from ETDataset will cause the parent_values.csv file to be removed. I understand this is used by ETLocal.

@michieldenhaan How is this file created? If it exists in ETDataset I can add it to the import script so that changes are imported with the rest of the dataset. If not, I think it might have to be moved to a new directory.

**Comment by michieldenhaan** [comment]
This file was created manually with the following query:
``TXT_TABLE(ALL(),key, demand, input_of_electricity, input_of_network_gas, input_of_coal, input_of_crude_oil, input_of_wood_pellets, input_of_steam_hot_water, input_of_coal_gas, input_of_useable_heat, input_of_hydrogen, input_of_diesel, input_of_biodiesel, input_of_gasoline, input_of_bio_ethanol, output_of_useable_heat)``

The file is mainly used to allocate a certain share of the NL steel/aluminium/refineries/fertilizers to a local dataset. Due to certain nodes in these sectors with specific carrier input ratios the user cannot freely set carrier demands for these sectors (see https://github.com/quintel/etlocal/issues/72).

I'm happy with moving it to a new directory. I think it's not so trivial to generate it in ETDataset since it contains information on nodes quite 'to the left' in the graph, e.g. electricity input of ``industry_aluminium_electrolysis_bat_electricity``. But it's not impossible. In the future, we probably want to have a separate parent_values.csv for NL2016, so in that sense it is nice if it's linked to the dataset in some way.

Maybe @ChaelKruip or @jorisberkhout have an opinion on this?

**Comment by ChaelKruip** [comment]
> Maybe @ChaelKruip or @jorisberkhout have an opinion on this?

Whatever seems most clean and maintainable is alright we me. I think @jorisberkhout is more at home in this region of the model. I'll trust his judgement.

**Comment by antw** [comment]
> I would suggest to move this file to /datasets. 

I think the file contains demands and shares specific to NL. Perhaps it could be moved to `/datasets/nl` alongside the central producers and primary production CSVs?
