### ISSUE TITLE
Refinery fails on woody biomass max_demand for local dataset

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1809]
Refinery throws the following error about ``max_demand`` of woody_biomass for a local dataset (branch: https://github.com/quintel/etsource/tree/fryske-marren)

![failed build 1 of etsourcefryske-marren - semaphore httpssemaphoreci com 2018-09-07 09-37-32](https://user-images.githubusercontent.com/32056448/45207057-2112a800-b287-11e8-9bff-4904bdc5f684.png)

I had this before with 2 Groningen neighbourhood datasets. The mismatch was a little bit bigger there (i.e. it was noticeable in the error report). Slightly lowering biomass demand solved the issue there.

I'm not sure what causes this issue and what the function of ``max_demand``  is. ``max_demand`` is not set in local datasets and it's totally fine if biomass is imported if some maximum is exceeded.

**Comment by antw** [comment]
In this case the error was caused by `max_demand` being a floating point number, and so small errors can creep in during the calculation. Changing it to a high-precision number fixed this, but I don't think that's the correct fix since `max_demand` is not always a number: sometimes it is `Infinity` or `"recursive"`. I've simply relaxed the validation slightly so that tiny differences are no longer considered an error.

> I'm not sure what [..] the function of max_demand is.

It relates to a feature called "flex-max". Normally if you have a node with a single incoming flexible edge, the edge will take away any demand not already assigned to other edges:

```
+--------------------+  <-- share (0.6) --
| Node (demand: 100) |
+--------------------+  <-- flexible --
```

This situation is pretty obvious: the share edge gets 60 demand, therefore the flexible will get 40. It's also apparent that you cannot have multiple flexible edges otherwise there'd be no way to know how much demand to assign to each of them. Flex-max allows us to do this by assigning flexible edges a `priority` and `max_demand`†:

```
+--------------------+  <-- share (0.6) --
| Node (demand: 100) |  <-- flexible (priority: 2, max_demand: 10) --
+--------------------+  <-- flexible (priority: 1) --
```

This time the flexible edges get 10 demand and 30 demand respectively.

†  *the `max_demand` actually comes from the node to the right, rather than the edge itself*

---

In the case of woody biomass, the max demand of the energy distribution woody biomass node is inherited by the *outgoing* flexible edge and used when calculating energy flows into [the energy distribution wood pellets node](https://beta-engine.energytransitionmodel.com/data/930660/converters/energy_distribution_wood_pellets). It places an upper-limit on how much biomass can be produced domestically, with any deficit being imported:

<img width="777" alt="screen shot 2018-09-13 at 11 06 10" src="https://user-images.githubusercontent.com/4383/45482185-3be09300-b745-11e8-91ad-09fe36750d18.png">

**Comment by michieldenhaan** [comment]
Thanks!
