### ISSUE TITLE
Heat demand profile should be depended on the heat technology used

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#1922]
As mentioned in this pull request https://github.com/quintel/etsource/pull/1917#issuecomment-465032655 the current heat demand profiles for households are very spiky because they are based on gas-fired heaters. With district heating and heat pumps the house is heated in a very different way, more constant throughout the day. It would be good I think when the heat demand profiles would somehow dependent on the technology used.

**Comment by ChaelKruip** [comment]
> It would be good I think when the heat demand profiles would somehow dependent on the technology used.

If/when we do this we should perhaps also take into account the effect that residences with district heating will have a smoother aggregated profile because their behaviour averages out. This effect depends on the number of houses that share a network. 

Another effect which flattens the peaks of the supply profile of the district heating source is that heat networks have the ability to buffer heat. This will in effect flatten peaks and shift them in time. We need to take all these effects into consideration in one consistent approach IMO.
