### ISSUE TITLE
Primary demand of Export and Curtailment should only include net demand

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#2025]
@AlexanderWirtz pointed out to me that the primary demand mekko shows a lot of oil for "Export and Curtailment":
![image](https://user-images.githubusercontent.com/1303760/58030773-6e862b00-7b1f-11e9-8e4d-eb1e8dd665ae.png)

I always imagined that this mekko displays the **net** primary demand for NL caused by exported and curtailed carriers but it seems to show **all** primary demand instead as can be seen in [this query.](https://github.com/quintel/etsource/blob/master/gqueries/general/primary_demand/primary_demand_of_oil_and_derivatives_from_export.gql)

I would think we should calculate the net primary demand by doing this:
```
SUM(
       V(G(energy_export), "primary_demand_of_crude_oil - demand")
  ) / BILLIONS
```

So we don't count the exported stuff as primary demand.

@AlexanderWirtz, does this make sense? If yes, @marliekeverweij can you change this query and similar ones?

**Comment by AlexanderWirtz** [comment]
I also think the current chart is confusing. I am not an expert on how to calculate what we do want to put in there.

**Comment by marliekeverweij** [comment]
Maybe we should not show the primary demand of the exported fuels at all and only show the primary demand of the sector final demands and  That is in line with the CO2-emission calculation: we also do not take into account the CO2 emissions of exported fuels.

> `SUM(V(G(energy_export), "primary_demand_of_crude_oil - demand") / BILLIONS`

I think it's not a good idea to use this query. This query would kind of show the losses of the process from primary product -> exported fuel. I think that's not very interesting.

I think we should choose to either totally include the primary demand of export fuels or exclude it. What's our opinion on this @michieldenhaan ?

**Comment by marliekeverweij** [comment]
@ChaelKruip , @michieldenhaan and I just had a meeting about this issue. 

**Conclusion:**
The energetic losses related to the production of exported fuels are already included in the primary demand of the refinery sector. So the export-category should not be added to the primary demand mekko, since these losses will then be double-counted.

**Comment by marliekeverweij** [comment]
> **Conclusion:**
> The energetic losses related to the production of exported fuels are already included in the primary demand of the refinery sector. So the export-category should not be added to the primary demand mekko, since these losses will then be double-counted.

So shall I:
- Remove the primary demand of export from the primary demand mekko
- Add queries that only show the primary demand of curtailment
- Rename the category from 'Export & curtailment' to 'Curtailment'

@ChaelKruip @michieldenhaan @AlexanderWirtz ?

(Related issue that will also be closed when this issue will be fixed: https://github.com/quintel/etmodel/issues/3022)

**Comment by ChaelKruip** [comment]
> Add queries that only show the primary demand of curtailment

How about losses on the HV network due to exported electricity? Are they accounted for and if yes, where are they shown in the Mekko?

Great that you are picking this up @marliekeverweij!

**Comment by marliekeverweij** [comment]
> How about losses on the HV network due to exported electricity? Are they accounted for and if yes, where are they shown in the Mekko?

Good question. @michieldenhaan and I had a look at this and we found out that only the losses of refinery fuels are now double-counted in the mekko. So the network losses of other exported fuels (f.e. electricity and network gas) should be separately included in the primary demand mekko when we will remove the primary demand of export from the mekko! 

Proposal: let's add a new category to the primary demand mekko called 'Energy'. This category should include:
1. **Export losses** of fuels other than refinery fuels: 
We should make a query filtering for all exported fuels excl. refinery fuels.
2. **Energy-sector own use:** 
Currently this is secretly included in the [industry-category]( 
https://beta-engine.energytransitionmodel.com/data/latest/gqueries/gas_industry_in_mekko_of_primary_demand)
3. **Curtailment**

These modifications to the primary demand mekko should also be incorporated in this chart ([#45](https://beta-pro.energytransitionmodel.com/admin/output_elements/45)), because there the same things goes wrong with double-counting losses of exported refinery fuels: 

![Screen Shot 2019-05-28 at 12 11 03](https://user-images.githubusercontent.com/32833996/58470705-91799600-8142-11e9-8cdf-c953b90ce85b.png)

**Comment by michieldenhaan** [comment]
For the record, we do NOT want to show primary demand of exported fuels, electricity, heat, hydrogen etc. in the primary demand mekko, only their distribution losses @ChaelKruip, @AlexanderWirtz? 

I think it's more intuitive if we either:
- Do show primary demand of exported fuels, as part of the category 'Export'
- Remove the 'Export' sector from the Mekko and include distribution losses in the energy sector

**Comment by ChaelKruip** [comment]
> Do show primary demand of exported fuels, as part of the category 'Export'

I have the feeling that we are running in circles... @marliekeverweij didn't you remove this earlier?

> Remove the 'Export' sector from the Mekko and include distribution losses in the energy sector

I can get on board with this 👍

**Comment by ChaelKruip** [comment]
@marliekeverweij is this included in this deploy? It is not added to the milestone currently but it has the 'bug' label so perhaps it should?

**Comment by marliekeverweij** [comment]
@michieldenhaan @ChaelKruip and I do not know which way we want to go with this primary demand mekko. After the deploy we will have a meeting and make a decision about this mekko! So we will stop with 'emmeren' for now 😉
![Screen Shot 2019-07-04 at 11 26 21](https://user-images.githubusercontent.com/32833996/60655828-b7cfd700-9e4e-11e9-932b-fdacd64978e1.png)
(for @antw )
