### ISSUE TITLE
Should share-groups always have a 'flexible' edge?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2051]
@ChaelKruip and I were wondering if it is necessary for share-groups to always a `- type = flexible`-edge. We thought this was true, but found out that some share-groups do not have a `flexible`-edge and these share-groups seem to work fine.
For example: [ `households_useful_demand_light`](https://beta-engine.energytransitionmodel.com/data/latest/converters/households_useful_demand_light)

Notifying @antw :)

**Comment by antw** [comment]
It's not a hard requirement, no. If there is no flexible edge then the user (i.e. ETModel) is responsible for ensuring that the group sums to 100% by sending values for the entire group.

Personally I think it's a best practice to always have a flexible edge, since it ensures the model is consistent even when given invalid inputs from the user, but nowhere in the code is it required.

**Comment by ChaelKruip** [comment]
Thanks @antw!
