### ISSUE TITLE
The Agricultural biogas-CHP should not be part of the industry_chp merit-group

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#2095]
I think [this](https://github.com/quintel/etsource/blob/master/nodes/agriculture/agriculture_chp_engine_biogas.central_producer.ad#L9) is wrong but perhaps there is a good reason for this @AlexanderWirtz?

**Comment by AlexanderWirtz** [comment]
Looks like a mistake to me. I have no idea why it should be part of the industrial group. 

Could it be related to this?
I do know the biogas CHPs are different from the other types of CHP in that they 'dump' some of their heat. Only biogas CHPs do this typically. EnergyMatters says this is because biogas production through co-digestion must run pretty much non-stop for ideal yield. The demand for heat is (partly) seasonal, so part of the year (2000 hrs/yr) there is heat production, but no heat demand, meaning it is dumped.

One question: Should this attribute be set from the etdataset `node_source_analysis`?

**Comment by ChaelKruip** [comment]
@antw can you tell us how the merit.group is used? 

> One question: Should this attribute be set from the etdataset node_source_analysis?

@michieldenhaan do you know this?

**Comment by michieldenhaan** [comment]
> @michieldenhaan do you know this?

Do you mean the ``dumped_heat`` attribute? That is indeed an outcome of the node source analysis. The merit order attribute is not part of the source analysis but set manually I think.

**Comment by AlexanderWirtz** [comment]
> Do you mean the dumped_heat attribute? That is indeed an outcome of the node source analysis. The merit order attribute is not part of the source analysis but set manually I think.

Sorry, no. I meant the `merit_order.group`. And I wasn't asking how it was set, but whether it would make sense to set it from the node source analysis. This depends on @antw 's answer to https://github.com/quintel/etsource/issues/2095#issuecomment-518262030

**Comment by antw** [comment]
> @antw can you tell us how the merit.group is used?

`merit.group` is an anachronism, and should probably now be renamed to `merit.profile`. It tells ETEngine which profile to load for the producer (in this case industry_chp.csv) and has no other purpose.

**Comment by ChaelKruip** [comment]
> It tells ETEngine which profile to load for the producer (in this case industry_chp.csv) and has no other purpose.

I that case, this might be intentional as the industry might be more suitable for this type of CHP but I am not sure about the reasoning. 

Closing this as we are planning to abandon profiles for CHPs altogether.
