### ISSUE TITLE
The weather_properties.csv is not correct for default curve sets in most datasets

### ISSUE THREAD

**Issue by redekok** [quintel/etsource#2148]
Many of the curves in the default curves set for non-NL country datasets are symlinked to the `nl` ones. This is also the case for the `weather_properties.csv` file, which is not correct because the FLH should be country-specific.

**Comment by marliekeverweij** [comment]
@antw , is `weather_properties.csv` used when users click on the default weather year or are the FLH then derived from the `central_producers.csv`? Maybe we could delete it from the weather/default folder, since it now contains `nl` values (2015) in all (country) datasets and that is not correct

**Comment by antw** [comment]
> @antw , is weather_properties.csv used when users click on the default weather year

Yes it is. An alternative might be to wrap the whole "settings_weather_curve_set" input in an `IF` so that it isn't executed if the user reverts back to the default settings.

```ruby
IF(
  EQUALS(USER_INPUT(), "default"),
  -> {},
  -> {
      UPDATE(AREA(), weather_curve_set, USER_INPUT());

      x = WEATHER_PROPERTY(average_difference_in_air_temperature);
      heat_factor = 1.0 - 0.0893386 * x;
      cool_factor = 1.0 + 0.5669449 * x + 0.1598105 * x**2 + 0.0253755 * x**3 + 0.00163210 * x**4;

      # ...
  }
)
```

**Comment by redekok** [comment]
> An alternative might be to wrap the whole "settings_weather_curve_set" input in an IF so that it isn't executed if the user reverts back to the default settings.

This solution might be prettier than having the default FLH values documented in two places (both `central_producers.csv` and `weather_properties.csv`). What do you think @marliekeverweij?

**Comment by marliekeverweij** [comment]
I also like this solution!

However, I wonder how the curves and FLH will be updated to default with this `IF`. For example when users first choose 1987 and then want to return to default, I expect that with this `IF` that the FLH and curves will not be updated to default but still be 1987. Is that true @antw ?

**Comment by antw** [comment]
> For example when users first choose 1987 and then want to return to default, I expect that with this IF **the FLH and curves will not be updated to default** but still be 1987. Is that true @antw ?

Inputs always change *default* values in the graph to *something else*. If we skip the input with an IF, the graph will therefore retain the defaults.

**Comment by redekok** [comment]
@antw I was wondering if this solution has yet been implemented? It seems as if the tests for https://github.com/quintel/etsource/pull/2215 are failing because the `weather_properties.csv` can't be found for non-NL country datasets. I thought these didn't have to be present anymore in the default datasets?

**Comment by antw** [comment]
This hasn't been implemented yet: the query is as it was before, and I haven't changed the tests.

---

_Note to self: Tests will need to explicitly check for weather_properties.csv in all curve sets except for default. The tests as they are today will expect weather_properties.csv to _not_ be present, as they aren't part of the default curve set. However, we need to ensure that it is present for all non-default curve sets– and for all datasets – otherwise we would miss failures like that caught in #2215._

**Comment by noracato** [comment]
@antw @redekok I can pick this one up if you like

**Comment by antw** [comment]
> I can pick this one up if you like

If you don't mind, that would be great!

In addition to changing the query in [settings_weather_curve_set](https://github.com/quintel/etsource/blob/923eb253f2ef523f89f69bd1303def10312efe96/inputs/misc/settings_weather_curve_set.ad), we need:

* ... to change [the curve spec](https://github.com/quintel/etsource/blob/923eb253f2ef523f89f69bd1303def10312efe96/spec/curve_sets_spec.rb#L26-L35) so that it doesn't fail when the non-default curve sets (1987, 1997, etc) have a weather_properties.csv, even though the default one does not.

* ... to add a test which ensures that the non-default curve sets _do_ have a weather_properties.csv. Something like this perhaps (untested):

  ```ruby
  it 'has a weather_properties.csv' do
    expect(variant.curves.map(&:basename))
      .to include('weather_properties.csv')
  end
  ```
