### ISSUE TITLE
Input efficiency should be researched for MV batteries and OPAC

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2155]
While looking at this issue https://github.com/quintel/etmodel/issues/3135 I found out that the `~ input.electricity = 1.0 / 0.9` for MV batteries and OPAC was simply copied from `energy_flexibility_pumped_storage_electricity` and not separately researched.

**Comment by marliekeverweij** [comment]
After having contact with the client I found out that the current output efficiency for these technologies is actually the round-trip efficiency (= input efficiency * output efficiency). 

I propose to simply remove the `~ input.electricity = 1.0 / 0.9` from the MV batteries and OPAC. What do you think @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> What do you think @ChaelKruip ?

I'm fine with that but I'd feel better if @antw would give us his blessing as well because I don't fully recall the intricacies of the current split in input and output efficiencies. I can only imagine it having a use if after charging, a certain amount of energy leaks away. Otherwise one efficiency would suffice right?

**Comment by antw** [comment]
> I can only imagine it having a use if after charging, a certain amount of energy leaks away. Otherwise one efficiency would suffice right?

* **Input efficiency** `input.electricity`: energy leaks while charging.
* **Output efficiency** `output.electricity`: energy leaks while discharging.
* **Storage decay** `storage.decay`: energy decays / leaks while "idle" in storage.

Storage in Merit supports all three.

The current input efficiency means that for each 1J of excess, ~0.9J will be stored and ~0.1J will be lost. The current output efficiency (0.8) means that in order to meet a deficit of 1J, the battery has to discharge 1.25J (1J to meet demand, 0.25J is lost).

**Comment by ChaelKruip** [comment]
> Storage in Merit supports all three.

Thanks for the clarification! Am I correct to state that if `storage.decay` = 0.0 the following two give equivalent results UNLESS the storage capacity or volume are limiting factors:
* `input.electricity` = 0.5 **and** `output.electricity` = 0.5
* `input.electricity` = 0.0 **and** `output.electricity` = 0.25?

**Comment by antw** [comment]
> In both cases, for 1 output, you need 4 input.
>
> `input.electricity` = 0.5 and `output.electricity` = 0.5

Yes. 4 input × 0.5 = 2 stored × 0.5 = 1 output.

> `input.electricity = 0.0` and `output.electricity = 0.25`?

No. `input.electricity = 0.0` means you have 100% loss on input. If `input.electricity = 1.0` then you need 4 input to get 1 output.

4 input × 1.0 = 4 stored × 0.25 = 1 output.

I suppose the only material difference is that in periods of large excess, the buffer will fill up faster when the input efficiency is 100%, allowing other technologies a greater share of the excess. But that comes at the cost of being less effective when discharging, which might mean other flexibility options also have to discharge to meet demand, or dispatchables have to be used.

**Comment by ChaelKruip** [comment]
> No. input.electricity = 0.0 means you have 100% loss on input. 

🤦‍♂ Yes. I meant 1.0.

> I suppose the only material difference is that in periods of large excess, the buffer will fill up faster when the input efficiency is 100%, allowing other technologies a greater share of the excess. But that comes at the cost of being less effective when discharging, which might mean other flexibility options also have to discharge to meet demand, or dispatchables have to be used.

I prefer to err on the safe side here and not over-estimate the impact on discharging. In other words @marliekeverweij please go ahead as planned. I'm not sure if you should remove the whole line or simply set the input to 1.0.
