### ISSUE TITLE
Proposal: must-run nuclear plant should have zero marginal costs like other must-run plants

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2195]
This week we have implemented a toggle to make nuclear plants must-run instead of dispatchable. This works fine: electricity production change to a flat profile with maximum FLH. 

Only the marginal costs of nuclear plants stay the same and @AlexanderWirtz & I think it's logical to give must-run nuclear plants zero marginal costs like other must-run. This influences our hourly electricity price calculation. What do you think? economist @michieldenhaan and others :) 

![Screen Shot 2020-01-24 at 10 41 53](https://user-images.githubusercontent.com/32833996/73060009-3d70ae00-3e97-11ea-99a1-bb2f402c42d7.png)
![Screen Shot 2020-01-24 at 10 35 39](https://user-images.githubusercontent.com/32833996/73060019-406b9e80-3e97-11ea-8db4-b3cdc57f0bc6.png)

**Comment by ChaelKruip** [comment]
I tend to agree.

> This influences our hourly electricity price calculation.

Yes, but only if the nuclear power plant is price-setting. I think this probably only happens in cases where 

1. you have no other dispatchables (which generally have higher marginal costs) 
2. wind, solar and other must-run supply enough power to fulfil demand

In case 1, I think it should probably be that the price reflects the non-zero costs of running a nuclear plant. Otherwise you could just build nuclear and have free power and don't get compensated for the uranium that you have to buy :)
In case 2, I think the price of electricity should indeed be zero.

**Comment by michieldenhaan** [comment]
> I think it's logical to give must-run nuclear plants zero marginal costs like other must-run.

It really depends on what 'must-run' means in this context. If the nuclear power plant will produce electricity regardless of any external circumstances whatsoever then it does not have market power and is not price setting. However, this is a very extreme case and I'm not sure if that's the idea behind the new 'must run' toggle. In reality nuclear power plants will always respond to market conditions in some way or another (at least in all countries modelled in the ETM) and this will be reflected in the electricity price.

So I would prefer to leave the costs as they are at the moment.

**Comment by AlexanderWirtz** [comment]
> It really depends on what 'must-run' means in this context. If the nuclear power plant will produce electricity regardless of any external circumstances whatsoever then it does not have market power and is not price setting. However, this is a very extreme case and I'm not sure if that's the idea behind the new 'must run' toggle. In reality nuclear power plants will always respond to market conditions in some way or another (at least in all countries modelled in the ETM) and this will be reflected in the electricity price.

To me it is really not clear what causes this behavior. Is it because nuclear plants will provide power to P2G units if market prices are too low? Since their presence in the market will cause other dispatchable plants not to run, they do influence the market price, but I am unsure how. This seems like an excellent question to put to an experienced person like Bert den Ouden of Berenschot. He is also involved in the project for which this change was required. Let's ask him!
