### ISSUE TITLE
Present value of renewability and total energy should not return 0 in scenario report

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#2237]
The scenario report shows 0 for the present total energy and renewability

![image](https://user-images.githubusercontent.com/19907658/75670154-87aa3380-5c7c-11ea-8f22-e2748d6ed866.png)

I think this is because the queries used return 0 for present values.
This was changed to save time in this commit:
https://github.com/quintel/etsource/commit/4575cf44ca4aed4671b8fddc4d2824bc5641e96b#diff-4bda28d6c07fd10fd4f8a94bddf2a50e

This concerns these two queries:

- https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_renewability.gql
- https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_energy_demand_primary_of_final.gql

@antw is it ok if we allow these queries to return both present and future values?
Notifying @marliekeverweij

**Comment by antw** [comment]
> @antw is it ok if we allow these queries to return both present and future values?

No, these queries are used in the dashboard where only the future matters. We ignore the present because it speeds up every request to ETEngine (every slider movement responds faster).

The report can be adjusted to use the non-dashboard queries.

* Use `renewability` instead of `dashboard_renewability`

  For example:
  
  ```diff
  - {{ future.dashboard_renewability | times: 100 | round: 1 }}
  + {{ future.renewability | times: 100 | round: 1 }}
  ```

* Use `primary_demand_caused_by_final_demand` instead of `dashboard_ dashboard_energy_demand_primary_of_final`

  For example:

  ```diff
  - {{ future.dashboard_energy_demand_primary_of_final | autoscale: 'MJ' }}
  + {{ future.primary_demand_caused_by_final_demand | autoscale: 'MJ' }}
  ```

The queries have the same units, so it should be a simple case of swapping out one for another.
