### ISSUE TITLE
import:node should also update storage attributes

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2378]
Using the rake task to read updated specifications from ETDataset file to corresponding ETSource file does not function properly. Not all attributes that should be updated are updated, and some attributes that should be deleted are not deleted. Additionally, the order of attributes changes, so it is difficult to verify if all updates are read correctly by the rake task.

To give an example: the dataset containing the specifications for households batteries (households_flexibility_p2p_electricity) has been updated. Below I will give the changes that should be made for a few exemplary attributes, and describe what actually happens when the rake task is used.

output.electricity
- old value in ETSource: 0.85
- new value in ETDataset: **0.90**
- new value in ETSource after rake: 0.90
- This attribute is updated correctly

storage.decay
- old value in ETSource: 4.11e-05
- new value in ETDataset: **2.57e-03**
- new value in ETSource after rake: 4.11e-05
- This attribute is not updated correctly

hours_maint_nl
- old value in ETSource: 0.0
- new value in ETDataset: **None** (removed based on etdataset issue #852)
- new value in ETSource after rake: 0.0
- This attribute is not removed, though it should be

In the end I have updated the ETSource file manually. This is however prone to error, which is why the preferred option would be to have a properly functioning rake task.

**Comment by noracato** [comment]
@mabijkerk which rake task is this exactly? The `import:node` or ` import:dataset` task? (Or another one?)

**Comment by mabijkerk** [comment]
@noracato the `import:node` rake task.

**Comment by noracato** [comment]
Hi @mabijkerk! I looked at the task a bit:

> storage.decay [..] This attribute is not updated correctly

I'm unable to reproduce this one. If I change the value of this attribute to nonsense manually, and then run the task again, it gets nicely updated back to the value it should be. Could you give me some more info maybe?

> This attribute is not removed, though it should be

Fun fact: the task was correct not to remove it.

The task purposfully leaves all the data in and only updates existing or new values. This is because there are also values in the node that do not come from the `node_source_analysis` like the groups. The task is unable to remove anything from the node file because it doesn't know what data is valuable (`groups`) and what not (`house_maint_nl`).

We could add a whitelist somehow with the attributes that should not be dropped when they are not in the `node_source_analysis`, and have the task drop all other attributes. Or the other way around. But I'd need your help creating that list, as I don't know which exact attributes would apply.
