### ISSUE TITLE
Renewable electricity percentage should not be able to exceed 100%

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2391]
Currently it's possible that the renewable electricity % in the dashboard exceeds 100%. I think that's confusing.

Example: 
[https://pro.energytransitionmodel.com/saved_scenarios/9894
![Screenshot 2020-12-11 at 15 26 46](https://user-images.githubusercontent.com/32833996/101915002-52485400-3bc5-11eb-8c0c-c866d41b6d62.png)
](https://pro.energytransitionmodel.com/saved_scenarios/9894)

**Comment by mabijkerk** [comment]
In the query for this dashboard item it is stated that "Renewable electricity share according to the EU is the sustainable produced electricity divided by final demand of electricity". This aligns with the definition given by Eurostat (https://ec.europa.eu/eurostat/web/products-eurostat-news/-/DDN-20200129-1). If you have overcapacity in **volatile** renewable electricity, for example to enable hydrogen production, this dashboard item can then by definition exceed 100%.

I think changing it would be problematic, because even in your scenario you also have some electricity production from fossil fuels, so you can't say that the share of renewable electricity is 100%. What do you think?

On a more general level I think that this dashboard item is a bit outdated in terms of long term goals, given that the goals of the European Union now focus on reaching a certain share of renewable **energy** instead of **electricity**.

**Comment by ChaelKruip** [comment]
Excellent points @mabijkerk! Let's close this.
