### ISSUE TITLE
Flex charts should not respond to installing more power-to-gas 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2415]
@DorinevanderVlies pointed out today that the new flexibility charts change when changing the installed capacity of power-to-gas. 

In the screenshot below you can see the II3050 Regional with (right) and without (left) power-to-gas:
- without power-to-gas the chart shows excess hydrogen (negative values)
- with power-to-gas the chart shows shortage hydrogen (positive values)

![image (10)](https://user-images.githubusercontent.com/32833996/107989515-c1ca2d80-6fd2-11eb-9128-5556b543fc14.png)

@mabijkerk do you have time to look into this?

**Comment by DorinevanderVlies** [comment]
I don't really mind that they respond to sliders being set...
I actually thought they should and was surprised that they are meant to be fixed charts.
Notifying @ChaelKruip

**Comment by mabijkerk** [comment]
This behaviour is as expected because in our definitions, import is considered inflexible supply and export is considered inflexible demand. Both the import and export nodes are therefore also included in the inflexible converter groups for hydrogen. The effect is demonstrated below for the II3050 National Governance scenario:

When power-to-gas is set to 0, while keeping the hydrogen demand as is, backup hydrogen import is activated to balance the central hydrogen network (see chart on the left). Because this import is a flat curve, we have defined it as inflexible and consequently the inflexible hydrogen supply increases (see chart on the right).
<img src="https://user-images.githubusercontent.com/67338510/108057263-b3235b00-7052-11eb-88e6-60c85d2d610f.png" width=400> <img src="https://user-images.githubusercontent.com/67338510/108057411-e2d26300-7052-11eb-9a73-29c6fb22ab51.png" width=400>

When power-to-gas is set to a higher value, excess hydrogen is exported to balance the central hydrogen network. Because this export is a flat curve as well, we have again defined it as inflexible and the inflexible hydrogen demand increases.
<img src="https://user-images.githubusercontent.com/67338510/108061007-f9c78400-7057-11eb-889f-4773c888f011.png" width=400> <img src="https://user-images.githubusercontent.com/67338510/108061069-0fd54480-7058-11eb-9f42-3387335550cb.png" width=400>

I think the main point of discussion is whether our view of flat curves as 'inflexible' is correct. My view would be that technologies should be defined as flexible when they are deployed to ensure the balance of the energy system. The main question is at what timescale we place the scope of this definition: import and export of hydrogen are flexible from a yearly perspective, but inflexible from an hourly perspective.

**Comment by mabijkerk** [comment]
@DorinevanderVlies it is worth mentioning that these charts are only meant to be static if changes are made to flexible technologies. They **dynamically** show changes made for inflexible technologies. If a user for example installs more offshore wind turbines, these charts should change (and they do).

**Comment by DorinevanderVlies** [comment]
> @DorinevanderVlies it is worth mentioning that these charts are only meant to be 'fixed' when changes are made to flexible technologies. 

This confuses me a bit. Should the chart be fixed when I install batteries? They do change (see example below).
Just to be clear. The charts behave as I expect them to behave. My main confusion comes from the flex-team telling me that they should be fixed when I install flex technologies.

**Batteries in cars**
![image](https://user-images.githubusercontent.com/19907658/108089396-d7466280-7079-11eb-9458-d59e2a3cbc98.png)

**Comment by mabijkerk** [comment]
I think that in retrospect my previous answer was a bit too simplistic.

An example of what could have happened in your scenario: the installation of batteries (flexible technology) might decrease the availability of excess electricity, which in turn may cause the hydrogen production by power-to-gas (flexible technology) to decrease. In this case, to maintain the balance in the hydrogen network, hydrogen would be imported (inflexible technology). This import then shows in the charts as an increase of inflexible hydrogen supply.

This example indicates that you're right: it is indeed possible to affect these charts by making changes in flexible technologies. To therefore refine my previous answer: I think that changes in flexible technologies can only affect these charts **indirectly**, when they cause changes in inflexible technologies.

**Comment by DorinevanderVlies** [comment]
Ok, clear. So changes to flex technologies influence these charts because they influence the whole energy system.
All flex technologies I tried change these charts so I'll feel free to call them dynamic ;-).
