### ISSUE TITLE
Create connection with fertilizer sector (probably coupling node)

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2605]

**Comment by mabijkerk** [comment]
See discussion in https://github.com/quintel/etengine/issues/1222.

**Comment by mabijkerk** [comment]
I've added input statements for the fertilizers sector, but I'm running into an issue while setting the total demand. I have made the following input statement, [industry_chemicals_fertilizers_external_coupling_total_demand](https://github.com/quintel/etsource/blob/etm-ctm/inputs/modules/external_coupling/chemical_fertilizers/industry_chemicals_fertilizers_external_coupling_total_demand.ad):

```
- query =
    EACH(
      UPDATE(INPUT_SLOTS(V(industry_chemicals_fertilizers_haber_bosch_process_hydrogen),hydrogen), conversion, 0.0),
      UPDATE(INPUT_SLOTS(V(industry_chemicals_fertilizers_haber_bosch_process_hydrogen),not_defined), conversion, 1.0),
      UPDATE(INPUT_SLOTS(V(industry_chemicals_fertilizers_haber_bosch_process_hydrogen),useable_heat), conversion, 0.0),
      UPDATE_WITH_FACTOR(V(industry_chemicals_fertilizers_haber_bosch_process_hydrogen), preset_demand, USER_INPUT()),
      UPDATE(V(industry_useful_demand_for_chemical_fertilizers_coal_non_energetic), preset_demand, 0.0),
      UPDATE(V(industry_useful_demand_for_chemical_fertilizers_wood_pellets_non_energetic), preset_demand, 0.0),
      UPDATE(V(industry_useful_demand_for_chemical_fertilizers_crude_oil_non_energetic), preset_demand, 0.0)
    )
- priority = 0
- max_value = 1000.0
- min_value = 0.0
- start_value = 100.0
- step_value = 0.1
- unit = %
- update_period = future
- update_type = %
```

When I test this on a scenario by setting it to 50.0, the demand of the haber bosch node will drop accordingly, with 50%. The energy should then be passed to the not_defined input slots, which should be set to 100%, because this is where the external coupling nodes are attached. The input slots of hydrogen and useable_heat should be set to 0%. Even though I've included this in my input statement, the input slots do not change:

<img width="1484" alt="Screenshot 2022-02-08 at 09 43 01" src="https://user-images.githubusercontent.com/67338510/152950042-41321731-bfe3-418a-9ff6-8d991e6f5149.png">

This seems strange to me, since I use a similar input statement to set input slots for the external coupling nodes, for example [industry_chemicals_fertilizers_external_coupling_energetic_coal_share](https://github.com/quintel/etsource/blob/etm-ctm/inputs/modules/external_coupling/chemical_fertilizers/industry_chemicals_fertilizers_external_coupling_energetic_coal_share.ad), which **does** work. @antw antw @marliekeverweij does either of you know why the input statement for total demand isn't working as intended?

**Comment by antw** [comment]
Removing...

```
- update_type = %
```

... does the trick for me, though I'm not sure why. I'll try to find out.

I think you'll need to change the line that uses `USER_VALUE()` to account for the removed update_type:

```
UPDATE_WITH_FACTOR(
  V(industry_chemicals_fertilizers_haber_bosch_process_hydrogen),
  preset_demand,
  DIVIDE(USER_INPUT(), 100)
)
```

<img width="728" alt="Screenshot 2022-02-08 at 09 38 40" src="https://user-images.githubusercontent.com/4383/152959717-548958d6-387b-4bbf-b767-9e749d563a1c.png">
