### ISSUE TITLE
The heat network storage should store heat when switched on

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2627]
Heat storage is on in [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/11903) but does not appear to be being used/the graph indicates there is no data to display.

@antw, could you figure out what's going on?

![Screenshot 2022-02-09 at 10 55 31](https://user-images.githubusercontent.com/32833996/153172328-ceaeb119-71e3-42b5-8327-41ab8de63e1d.png)

**Comment by antw** [comment]
It's because all flexibility options in Merit are now controlled by their marginal cost and (optional) max consumption price. Heat storage has a marginal cost of 0 and no consumption price, which means it would only take in energy when the price of heat is less than zero (which is impossible).

If this is the only flexibility option in the heat network, I can just hard-code that storage has an infinite consumption price and it will work as it did previously. We may want a more robust solution if there are other flexibility technologies.

**Comment by mabijkerk** [comment]
On the supply side, storage is not the only option, because there are a lot of other flexible technologies. On the demand side, the only other flexible option is the unused steam hot water node.

My knowledge of the heat network modelling is not that extensive, but if it works in a way that is similar to the electricity network, then I would expect that setting an infinite consumption price for storage means that it is willing to pay anything to store heat. I would then expect that the flexible heat supply technologies would always be turned on and only be limited by the maximum input capacity of the storage, which would be undesirable. Or am I missing something here?

In principle I would expect that a consumption price of 0 would be better: heat should only be stored when there is **inflexible** heat production that is not already used by **inflexible** heat demand, or in other words, when there is excess heat production. I would expect the heat price to be 0 in those hours.

**Comment by marliekeverweij** [comment]
Interesting: when I turn the storage on in a blank NL scenario and put the biomass heater above the storage in the merit order list, the storage does work! See the scenario link[ here](https://pro.energytransitionmodel.com/saved_scenarios/11909).

![Screenshot 2022-02-09 at 15 58 24](https://user-images.githubusercontent.com/32833996/153227314-fc1fe1cb-0d63-4605-b110-7bf5fb0b0fae.png)

**Comment by mabijkerk** [comment]
Setting max consumption of the heat network storage node at 1000.0 euros in II3050 National Governance leads to a very large amount of heat stored - and subsequently unused heat.
<img width="500" alt="Screenshot 2022-02-21 at 09 48 36" src="https://user-images.githubusercontent.com/67338510/154919883-006e6dd3-3b51-45cd-bd0a-40f5870b5fd1.png">

Setting max consumption of the heat network storage node at 0.50 euros however seems to lead to more sensible behaviour.
<img width="500" alt="Screenshot 2022-02-21 at 09 52 55" src="https://user-images.githubusercontent.com/67338510/154920605-91adf609-80d7-48cc-a747-a432b3df0e56.png">

Based on the examples above I think that setting a very high consumption price, or even infinite, would not be desirable. This  artificially increases flexible (dispatchable) heat production, which is then only wasted.

I would think that heat should only be stored when inflexible supply exceeds inflexible demand. This was initially the case as well right? If so, then heat should be stored when the price is 0. However, for electricity I think we have decided that when the electricity price is 0 and equal to a flexible consumption price of 0, then the flexible demand technology should not be allowed consume. This was done to prevent export in hours of excess electricity where the neighbouring country would also have excess electricity. It also explains why there is suddenly no storage with a consumption price set to 0. This would mean that heat storage is only activated when the consumption price is slightly above 0.

**Comment by antw** [comment]
@marliekeverweij @mabijkerk Check out [the **issues/etsource-2627** ETEngine branch](https://github.com/quintel/etengine/tree/issues/etsource-2627).

This should fix both problems:

1. Heat storage doesn't work when assigned to the first position in the heat network order because we abuse the `marginal_costs` attribute, allowing the user to order the technologies as they desire. The first option would be assigned `0`, which means it never gets any energy (for the reason @mabijkerk already explained). This has been fixed by simply assigning the first technology to `1`, the second to `2`, etc.

2. Flexible technologies in the heat network order will no longer consume energy from dispatchables based on price (since they don't have a price). They'll only consume *excess* heat.
