### ISSUE TITLE
typo "industry_chemical_other_captured_co2_electricity.input (MW)"

### ISSUE THREAD

**Issue by robcalon** [quintel/etsource#2643]
Seems to be missing an "s" like other parameters in industry_chemicals.

**Comment by antw** [comment]
@lottevanvlimmeren Can you take a look at this when you have time? It seems [when the CCUS nodes](https://github.com/quintel/etsource/commit/b775b05ba539c1cd90845e8798a06c90c45c816c#diff-65dcd666d32317b3a5fc44e324d0b468d0cf2ede5e83faf46bf0ff31d723f7e2) were added this one was given the prefix "industry_chemical" instead of "industry_chemicals". I'm guessing that wasn't intentional?

TY!
