### ISSUE TITLE
Is it possible to query the hourly emission intensity of electricity production?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2650]
The client has the wish to calculate the average emissions for:
- P2H boilers in industry: emissions / produced heat
- central elektrolyzer: emissions / produced hydrogen

For this we would need an hourly curve with the emission intensity of electricity production. We are curious if this is possible without too much effort. If this takes too much time, then they will calculate it in the CTM, so it's optional.

**Comment by marliekeverweij** [comment]
@antw do you have time to have a look at this? Sorry, I forgot to notify you in the previous message I see now

**Comment by antw** [comment]
> I am looking for an hourly curve with the actual emissions of electricity production in each hour

I think the answer is that this is very difficult to do in the ETM. We've sometimes talked about an hourly graph as the solution to calculating exact hourly emissions. Since that is nowhere near happening, the only possibility would be to build emissions curves on each electricity producer, then find some way to use RecursiveFactor to calculate the emissions for each consumer for every hour. Personally, I don't think that is actually a viable approach.

**Comment by marliekeverweij** [comment]
Good to know @antw !

**Comment by mabijkerk** [comment]
@antw which part would be more difficult to implement: adding emission curves on each electricity producer or implementing a recursive method? For both I can think of other ways to obtain the same result:

**Emission curves**
For each producer we could query the hourly electricity production, divide it by the efficiency of the producer and multiply it by the emission factor of the fuel input. We could then query the sum all of the emission curves and divide it by the total electricity production to get the hourly emission intensity of electricity production.

**Recursive factor**
If we already have the emission curves, we could simply sum all of the emission curves and divide it by the total electricity production to get the hourly emission intensity of electricity production. I don't see why we need a RecursiveFactor for this - similar to the hourly electricity price, the hourly emission intensity is a property of electricity supplied from the grid that **all** consumers get. For example, in a given a hour for electricity taken from the grid the price may be 40 euros/MWh and the emission intensity 0.464 kg CO2/MWh.

If adding emission curves would be relatively straightforward, then I would simply query the emission intensity, instead of adding a recursive factor.

**Comment by mabijkerk** [comment]
**Emission curves**
To give an idea of the emission curve I have written a query that determines the hourly co2 emissions of the `energy_chp_ultra_supercritical_coal`:

``` ruby
PRODUCT_CURVES(
    COALESCE_CURVE(
      nil,
      PRODUCT(
        DIVIDE(1,V(energy_chp_ultra_supercritical_coal, electricity_output_conversion)),
        V(energy_chp_ultra_supercritical_cofiring_coal,coal_input_conversion),
        MJ_PER_MWH,
        V(CARRIER(coal),co2_conversion_per_mj)
      )
    ),
    V(energy_chp_ultra_supercritical_cofiring_coal,electricity_output_curve)
)
```

**Comment by antw** [comment]
Thanks for clarifying @mabijkerk. Perhaps I was misunderstanding the original question.

> I am looking for an hourly curve with the actual emissions of electricity production in each hour

I'm still not sure I understand the distinction between `primary_co2_emission` and "actual emissions".

It _sounds_ from @mabijkerk's example that you want to disregard any emissions which occur to the right of the electricity producer, and only consider emissions that occur on the producer itself?

**Comment by mabijkerk** [comment]
I think there are two ways to define the emissions. The "actual emissions" I would define as the direct or on-the-spot emissions i.e., the emissions that occur at a power producer / within a power plant. These emissions are based on the direct fuel input.

The primary emissions are then based on the primary fuel input. This indeed means that they take into account all the emissions that occur to the right of the electricity producer as well.

I think conceptually we would have to decide which type of emissions to calculate, and be transparent about it whenever we use the hourly co2 intensity of electricity. For now it would be interesting for both types of emissions to know what it would take to implement this calculation.

**Comment by antw** [comment]
> I think there are two ways to define the emissions. The "actual emissions" I would define as the direct or on-the-spot emissions i.e., the emissions that occur at a power producer / within a power plant. These emissions are based on the direct fuel input. In my example I was talking about the on-the-spot emissions.

Thanks. I imagine it's not too difficult to create an emissions curve for the direct emissions. [Your query above](https://github.com/quintel/etsource/issues/2650#issuecomment-1100117714) should be easy to adapt to account for all the input carriers on a node. I agree that it makes more sense for this to be done in Ruby, rather than in GQL:

```ruby
V(some_node, direct_co2_emission_curve)
AVG(V(some_node, direct_co2_emission_curve))
```

For a curve of the primary CO2 emissions, I still imagine we'd do something like this (I don't know how comfortable you are with Ruby, hopefully this makes sense):

```ruby
# Get the primary CO2 emission per MWh of demand on the node.
co2_per_mwh = primary_co2_emision / demand * MJ_PER_MWH

# .map iterates through each value in the curve, transforming it to another value
# (whatever is returned by the do..end block).
electricity_output_curve.map do |electricity_in_hour|
  # Convert the electricity output for the current hour (MWh) to the equivalent
  # demand (MWh) on the node
  demand_in_hour = electricity_in_hour / electricity_output_conversion

  # Multiply the demand (in MWh) by the CO2 emissions per MWh to get the
  # amount of primary CO2 emission in this hour.
  demand_in_hour * co2_per_mwh
end
```

```ruby
V(some_node, primary_co2_emission_curve)
AVG(V(some_node, primary_co2_emission_curve))
```

**Comment by mabijkerk** [comment]
On hold until it can be picked up within the hydrogen modelling improvements.

**Comment by mabijkerk** [comment]
It is now possible to query an emissions curve. On ETEngine [emissions_curve.rb](https://github.com/quintel/etengine/blob/master/app/models/qernel/node_api/emissions_curve.rb)

This new method has been used to query the hourly CO2 emissions of electricity production. On ETSource [hourly_co2_emissions_of_electricity_production.gql](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/category_bar_co2_intensity_of_hydrogen_production/hourly_co2_emissions_of_electricity_production.gql)
