### ISSUE TITLE
Expand real_estate CSVs to calculate high insulation level costs

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2871]
**Background**
In the dataset for Northern-Ireland, the insulation sliders for households and buildings can go up to 75%. In https://github.com/quintel/etsource/issues/2815 the intention is described to make this the standard maximum value for all datasets, and to remove the dataset dependency.

**Issue**
One issue that should be tackled before that is the issue of costs. In [Atlas](https://github.com/quintel/atlas/blob/master/lib/atlas/dataset.rb#L270-L279) the function is defined that is used to retrieve the insulation costs. It refers to the folder `real_estate`. Northern-Ireland does not have this folder, so it retrieves it from `eu`, which in turn retrieves it from `nl`.

The issue is that the CSVs containing these costs stop at a certain percentage, and this percentage is dictated by the `nl` dataset. For example, for [corner houses](https://github.com/quintel/etsource/blob/master/datasets/nl/real_estate/insulation_costs_existing_corner_houses.csv), the CSV only goes to 69%.

The result is that, going from 68% to 69% insulation in for corner houses in a scenario for Northern-Ireland increases the insulation costs, but going from 69% to 75% no longer does:

```ruby
Q(costs_of_insulation_corner_houses)

68%: 2,236,703,374.571671
69%: 2,269,917,043.458064
75%: 2,269,917,043.458064
```

**Solution**
We should add new costs figures for higher insulation levels. In this commit it has only been done for new builds: https://github.com/quintel/etsource/commit/3f9c92968f4c191ab0e3ec850434003f1bc70bab

**Comment by DorinevanderVlies** [comment]
### Summary of current approach

Full description is on [docs](https://docs.energytransitionmodel.com/main/insulation/). Below a summary.

The current insulation level (with heat demand reduction) and corresponding costs comes from:

- Households: Interpolation between 0% reduction and two points (medium and high reduction) ECN.  The insulation is now limited to the heat reduction corresponding to insulation level "high". 

- Buildings: euro/% of heat reduction. Source: Vesta 2016 in combination with weighted average of floor area (ECN)

<img width="372" alt="image" src="https://github.com/quintel/etsource/assets/19907658/26005449-57f4-4f8b-ba56-b0c0a97a7869">

### Quick fix for extending the range

- **Buildings**: I propose to make a full range from 0 to 75% using the current linear cost parameters instead of the current flat line after 69%.
- **Households**: I propose to extrapolate from "high" to 75% using the slope derived from the step from "medium" to "high". 

@mabijkerk if you agree I can implement this next week. 

<img width="1419" alt="image" src="https://github.com/quintel/etsource/assets/19907658/607ad06d-4e2c-44b5-b31e-eed3a849919a">

### Future options for insulation costs

I have not thoroughly researched other options. A quick research taught me that:

- **Hestia** provides very detailed data about effect of heat demand reduction measures and their costs. However, I do not (yet) see an easy to use overview.
- **[Energy.nl](https://energy.nl/datasheets/?Wordpress%5Bquery%5D=insulation&Wordpress%5BrefinementList%5D%5Btype.name%5D%5B0%5D=Datasheet)** provides datasheets for insulation of apartments, terraced houses and other dwelling types (detached houses, semi-detached, and corner houses). I have not yet found datasheets for insulation of buildings.

**Comment by mabijkerk** [comment]
Thanks for looking into this @DorinevanderVlies, next time I'll look at our own documentation first!

I agree with your suggested quick fix. At this point I would not pursue any other options, but it is good to know that there is some data out there.

As I understand it, the households costs consist of two linear lines and the buildings only of one. The costs do not differ between datasets right? All dataset either refer to the `nl` or the `nl2019` costs and those seem to be the same as well. A final question from me is therefore if we shouldn't simply remove the entire module and just write two queries to specify these costs. The current structure with Atlas that retrieves CSV file seems overly complicated, when we can use a simple IF query to determine in which range the insulation input value falls. What do you think @DorinevanderVlies?

**Comment by DorinevanderVlies** [comment]
> The current structure with Atlas that retrieves CSV file seems overly complicated, when we can use a simple IF query to determine in which range the insulation input value falls. What do you think @DorinevanderVlies?

Sounds like a good planI actually think that the curves for households are linear enough to model them with one slope (for each house type).

**Comment by mabijkerk** [comment]
This issue is no longer relevant after the recent modelling changes for heat in the built environment. Insulation queries have been rewritten to no longer use the extensive CSV indicated here. Instead, we now simply use two lines in the style of y = ax + b to  model insulation costs (which was exactly the underlying method in the CSV).

See for example https://github.com/quintel/etsource/blob/master/gqueries/general/costs/mece_costs/1_building_and_installations/insulation/costs_of_insulation_apartments_1945_1964.gql
