### ISSUE TITLE
Greengas backup export node missing

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etsource#2986]
In the model, energy_distribution_greengas has 2 outgoing edges to the nodes : energy_national_gas_network_natural_gas, and energy_export_greengas_baseload. It has 4 incoming edges , with 3 of those coming from nodes that can be set as shares by the user in the model. Only taking these first three edges into account, there won't be any need for a backup greengas export since the demand will set the supply.
The 4th incoming edge is from the node industry_residual_greengas. This node can only supply greengas to the distribution when the CTM is coupled with the ETM. As the name suggests, residual greengas from the industry is supplied to the node. 
If you open the node in the[ II3050 v2 - Decentral incentives scenario ](https://energytransitionmodel.com/saved_scenarios/14552), you will see the following : 
<img width="1294" alt="Screenshot 2024-01-05 at 10 14 20" src="https://github.com/quintel/etsource/assets/150331345/2e3288b6-6fd6-48a9-bdee-688c8f479316">

If we than set the industry_residual_greengas to 50 PJ, the following occurs: 
<img width="1357" alt="Screenshot 2024-01-05 at 10 05 26" src="https://github.com/quintel/etsource/assets/150331345/b130c1ef-b098-4361-894f-e14b531dbff8">

This leads to two issues, one described in #2987.

The second issue: 
As can be seen the excess energy from industry_residual_greengas has nowhere to go. Thus to make the energy balance correct again we need to add a greengas backup export node.

Notifying @mabijkerk, will pick this up myself.

**Comment by kaskranenburgQ** [comment]
While reviewing this we discovered that this issue is more complicated then we initially thought. Adding a backup greengas export node as the other export nodes are modeled leads to an error in the graph. 

There could be 2 possible reasons:

1.  The data initialisation of greengas production in the graph could lead to some issues. This is not as straightforward as we thought.

2. In the prefered modeling route greengas is exported as the carrier network gas. This is due to the mxture of greengas and natural gas in the network. In the current state of the model natural gas is also exported as network gas. It could be that the graph does not allow to 2 flexible export nodes of network gas. 

Will need to investigate these 2 further.

**Comment by mabijkerk** [comment]
There are a number of additional points about the modelling of green gas and natural gas:

- Preferably users would import and export network gas, currently they import natural gas and export natural gas and green gas. Import of green gas is not available
- A transit flow from import to export without any local demand would still require infrastructure. At the moment this is not the case, since import and export is handled 'before' the national gas network node
- There have been some users who have indicated that they would rather set green gas production, instead having green gas production follow from demand
- If a user currently sets baseload network gas demand, this is distributed across the green gas baseload and the natural gas baseload nodes according to the share of green gas in the gas network. In practice, this does not mean that all export has the same mix as the share of green gas in the gas network because there is also a backup natural gas export node

All the point mentioned in this issue indicated that we should:

- [ ] Make a thorough analysis of the issues with green gas, natural gas and network gas
- [ ] Make an inventory of desired modelling of green gas, natural gas and network gas
- [ ] Make a new conceptual design that meets desired modelling
- [ ] Implement new conceptual design

**Comment by kaskranenburgQ** [comment]
We have been working on this issue within the ctm-etm-coupling project. Our approach seems to work, however as @mabijkerk describes it: 

> removing demand = 0.0 from the green gas backup export node crashes the graph because the green gas distribution node is then underdimensioned. We should update the data pipeline for green gas at some point, using the transformation flows on the Eurostat energy balance

More work on the data pipeline is therefore necessary
