### ISSUE TITLE
hydro_river is too reliable in Security of Supply chart

### ISSUE THREAD

**Issue by Richard-Deuchler** [quintel/etsource#309]
Renewable electricity production is shown to be extremely reliable (loss of load) in the `Security of Supply` chart: 

![screen shot 2013-06-24 at 11 03 30](https://f.cloud.github.com/assets/2749265/694318/12e27cde-dcad-11e2-81fc-1228030f7acd.png)

A look into the [converter.ad](https://github.com/quintel/etsource/blob/master/data/nodes/energy/energy_power_hydro_river.converter.ad?source=c#L14) shows that `river_hydro` has a variability of only 1.5% (compare with > 80% for wind). 

to do: 
- [ ]  were does that number come from?
- [ ] what would be a better number?

**Comment by jorisberkhout** [comment]
This issue is no longer relevant since the new implementation of the LOLE calculation. The production profile for hydro river is considered volatile and scaled by the installed hydro river capacity in the scenario. This production is subtracted from the load or demand profile just like all other volatile production. The residual demand profile is compared to the dispatchable production capacity to determine the LOLE.
