### ISSUE TITLE
Electric vehicles need 'additional costs'  attribute wrt fossil fueled cars

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#800]
After discussions with Ecofys we agreed to investigate the possibility of including  a costs parameter for vehicles.  Currently, the assumption is that vehicles cost the same regardless of their drive train technology. 

Because it would create different (unrecognized) cost numbers in the dashboard, I suggest instead of giving all cars and trucks cost attributes, we instead give them only to electric ones, in the form of `additional_costs`. This only applies to `installation costs` or a similar parameter, of course, as fuel costs are  taken care of automatically.

@jorisberkhout @wouterterlouw @ChaelKruip please comment. The data will be supplied by Ecofys.

Also see #797

**Comment by jorisberkhout** [comment]
Reopening this issue as I would like to validate the node source analysis before closing it. The current status of all node source analyses is documented in [this Dropbox file](https://www.dropbox.com/s/dah2t2wo9u2x2e0/20150120_status_overview_node_source_analyses.xlsx?dl=0).

**Comment by jorisberkhout** [comment]
@mariatsagkaraki has updated the specs in https://github.com/quintel/etdataset/commit/68a07e93e7ebf66bb26efe7aa8ab951dc98451fc. Assigning myself to validate.

**Comment by jorisberkhout** [comment]
Changing milestone to 'NL 2013 update' as I will not manage to implement this before the 'data freeze'

**Comment by jorisberkhout** [comment]
@RobTerwel and I discussed this issue with John. John agrees that we currently underestimate the costs of electric cars, and is also wary of adding high, unrecognisable costs to existing scenarios as a consequence of adding (additional) costs for cars.

Instead of giving electric vehicles a default `additional_cost` attribute, John proposed to add a slider by which the user can set the additional costs of electric vehicles with respect to gasoline/diesel cars and set this slider to `0` by default. This means that it will not have any effect on existing scenarios, but will give the user the opportunity to refine his scenario by including additional costs for electric cars.

This issue is also relevant for hydrogen cars, which @RobTerwel is currently including in the model. John suggested to use the aforementioned slider to also set the additional costs for hydrogen cars, i.e. one slider to set the additional costs for EV / FCEV.

I quite like this solution. What about you @AlexanderWirtz , @dennisschoenmakers and @ChaelKruip ?

**Comment by dennisschoenmakers** [comment]
Excellent idea IMO

**Comment by AlexanderWirtz** [comment]
I like it too. This will need a good write up in the ?  text to make sure we cannot be accused of bias.
This then requires some research and sources to refer too. @RobTerwel your research has probably already resulted in some eminently citable source also for electric vehicles, right?

We would of course also need a similar slider for H2 vehicles, n'est-ce pas?

**Comment by ChaelKruip** [comment]
> We would of course also need a similar slider for H2 vehicles, n'est-ce pas?

I think @joris has answered this in the negative:

> i.e. one slider to set the additional costs for EV / FCEV.

**Comment by AlexanderWirtz** [comment]
> I think @joris has answered this in the negative:
indeed!

**Comment by RobTerwel** [comment]
> @RobTerwel your research has probably already resulted in some eminently citable source also for electric vehicles, right?

Yes, I've acquired a substantial amount of sources which compare car technologies in many respects, including costs/cost projections.

> We would of course also need a similar slider for H2 vehicles, n'est-ce pas?

Oui, on en a besoin! Joris indeed proposed using  one slider with which the costs for both could be changed simultaneously, but the cost  difference  between EVs and FCEVs is quite significant as of now (mostly due to tanks and the fuel cell stack). We might as well make two sliders, one for the EV cost difference and one for the FCEV cost difference, to do justice to that. Especially in a 2025 scenario it is conceivable their investment costs are still far apart.

**Comment by jorisberkhout** [comment]
> I think @joris has answered this in the negative:

Indeed, John suggested to use just one slider for both. However, if the costs are far apart as @RobTerwel is suggesting, I will try to convince John to introduce two sliders.

**Comment by AlexanderWirtz** [comment]
John is fine with two sliders if the research points to big cost discrepancies between EV and FCEV. 

Let's try and include links to all the relevant documentation on etdataset and to reports in Refman. This way we can be as transparent as possible and make sure we help users decide what these slider settings should be.

**Comment by AlexanderWirtz** [comment]
PS just spent a day with John in Groningen. We discussed this there.

**Comment by jorisberkhout** [comment]
Assigning @RobTerwel to pick this up after all other Hydrogen related issues are closed.

**Comment by jorisberkhout** [comment]
Moving to 'Deploy February 2016' milestone.
