### ISSUE TITLE
FLH for HH Solar Water Heaters should be country-specific, not technology-specific 

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etsource#926]

**Comment by dennisschoenmakers** [comment]
As discussed with @AlexanderWirtz

**Comment by dennisschoenmakers** [comment]
See https://github.com/quintel/etsource/blob/master/nodes/households/households_water_heater_solar_thermal.converter.ad

**Comment by AlexanderWirtz** [comment]
First question to be answered: do these FLH do anything? If so, what? Are they used to determine the number of units, to make sure no more units can be installed than # of HH?

**Comment by jorisberkhout** [comment]
Good point, @dennisschoenmakers . I will look into this after my holidays.

**Comment by jorisberkhout** [comment]
Moved to 'Deploy February 2016' milestone.

**Comment by jorisberkhout** [comment]
Removing the milestone as this is not deploy-critical.

**Comment by jorisberkhout** [comment]
Removing milestone.

**Comment by redekok** [comment]
Can we use the FLH of `energy_heat_solar_thermal` for `households_water_heater_solar_thermal` as well? If so, should we add this producer to the `central_producers` table?

Notifying @michieldenhaan @DorinevanderVlies

**Comment by DorinevanderVlies** [comment]
> Can we use the FLH of energy_heat_solar_thermal for households_water_heater_solar_thermal as well?

Yes, I think we can. 

> If so, should we add this producer to the central_producers table?

Yes, I suppose we can/should also assign the solar thermal curve to the node and add this node to weather curves

**Comment by marliekeverweij** [comment]
Good idea! 

It would be even better if we could add the solar thermal production profile to `households_water_heater_solar_thermal` and add this to Fever! But I guess this is not easily done, since an extra step should be added to Fever I guess

1. Subtract the solar thermal production profile from the heat demand profile
2. Run Fever (I had written down the steps last year: https://github.com/quintel/documentation/blob/master/general/fever.md. When it's not clear or correct, let me know! @antw )

Related issue: https://github.com/quintel/etsource/issues/344
