### ISSUE TITLE
There should be only one number_of_residences

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etsource#946]
Currently we have for nl.ad:

```
- number_of_residences = 7386743.0
...
- number_of_new_residences = 1647243.7
- number_of_old_residences = 5739499.3
```

The latter two sum up to the first one, but it would be more consistent if we only have the latter two, right @antw, @ChaelKruip and @jorisberkhout ?.

Including @AlexanderWirtz

**Comment by ChaelKruip** [comment]
:+1:

**Comment by antw** [comment]
Alternatively:

```
- number_of_residences = 7386743.0
- proportion_of_old_to_new_households = 0.223
```

Eliminating `number_of_residences` likely has knock-on effects for scenario scaling, but I guess it is easier to update if you want to add "new" households since you don't have to recalculate the proportion of old-to-new. I don't have a strong opinion either way.

**Comment by dennisschoenmakers** [comment]
I like your idea even better than mine, @antw

**Comment by jorisberkhout** [comment]
I like @antw's suggestion as well as this is closest to the research data. In the `residences_analysis` we determine `number_of_old_residences` and `number_of_new_residences` from the total number of residences and a percentage of old/new residences.

**Comment by AlexanderWirtz** [comment]
Old houses get torn down and new ones built. Both are needed to calculate the proportion, but I am fine with Anthony's suggestion, especially if that is what we do in the dataset generation.

**Comment by ChaelKruip** [comment]
I remember that we have had a lot of trouble with the update statements that use the `number_of_residences` attribute. The trouble was that some inputs (e.g., `number_of_..._residences`) needed to be executed first in order to have the correct values for the roof surface etc. Whatever we change the current situation into, we need to make sure that this dependency still works.

Also see https://github.com/quintel/etengine/issues/599

**Comment by jorisberkhout** [comment]
Moved to 'Deploy February 2016' milestone.

**Comment by jorisberkhout** [comment]
Not deploy critical, removing the milestone.
