### ISSUE TITLE
Near future gas forward curve still acurrate?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etsource#955]
With the new projected production in the *near* future, is our [gas forward curve]( https://github.com/quintel/etsource/blob/master/datasets/nl/time_curves/energy_extraction_natural_gas_time_curve.csv) for the Netherlands still a good guesstimate?

**Comment by AlexanderWirtz** [comment]
It is NOT accurate, but until EBN and the government commit to a new one, it makes little sense to change it.

**Comment by dennisschoenmakers** [comment]
Should we convert this into a slider?

**Comment by ChaelKruip** [comment]
> Should we convert this into a slider?

This is a nice idea but it raises several questions to which I don't know the answer:

* What should the start value of the slider be? 'The current value' is likely not a good guess because it will generally be in conflict with existing reserves: gas reserves would run out within ten years if we would keep extracting at the current rate (roughly) for example.
* Given the previous question, should we inform the user of the (estimated) reserves for carriers so they can make a well-founded decision? This would be interesting although it would take quite a bit of research I presume. It would raise another question though:
* What do we assume for the years in between present and future? This becomes relevant if we will relate the extraction and the reserves.

**Comment by dennisschoenmakers** [comment]
> What should the start value of the slider be? 'The current value' is likely not a good guess because it will generally be in conflict with existing reserves: gas reserves would run out within ten years if we would keep extracting at the current rate (roughly) for example.

I would start with the value that is currently used and dictated by the forward curve. 

On your other two points: yes, it would be very informative to provide the user with 'proven' 'recoverable' reserves.

I think it would already be a step in the right direction if we would allow the user to change our current assumption about the future annual production.

**Comment by jorisberkhout** [comment]
> I would start with the value that is currently used and dictated by the forward curve.

I like that idea a lot!

> On your other two points: yes, it would be very informative to provide the user with 'proven' 'recoverable' reserves.

We could point the user to the **Production curve for natural gas** and urge him to think (even harder) about changing the slider setting.

**Comment by ChaelKruip** [comment]
> I would start with the value that is currently used and dictated by the forward curve.

I like that idea too. But I would be even happier with a solution that would make the ETM independent of forward curves altogether.

> I think it would already be a step in the right direction if we would allow the user to change our current assumption about the future annual production.

:+1:

**Comment by dennisschoenmakers** [comment]
> I like that idea too. But I would be even happier with a solution that would make the ETM independent of forward curves altogether.

Me too!

**Comment by AlexanderWirtz** [comment]
proven or recoverable reserves is not really a fixed number. It swings wildly with the gas price. These numbers are just about impossible to find or pin down definitibely.

**Comment by jorisberkhout** [comment]
Closing this as there is a redundant issue on ETDataset (https://github.com/quintel/etdataset/issues/623).
