### ISSUE TITLE
Weighted average of insulation fraction should be between 0 and 1

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#997]
In [this line](https://github.com/quintel/etsource/blob/one-node-hhp/inputs/demand/households/households_misc/households_insulation_level_new_houses.ad#L23) the definition is such that the insulation_fraction_weighted_average can become 2.
Dividing by 2 in the denominator would fix this.

**Comment by RobTerwel** [comment]
It seems to me that the max. value the insulation_fraction_weighted_average can have is 1.

``` insulation_fraction_weighted_average = (insulation_fraction_new_houses * households_number_of_new_houses + insulation_fraction_old_houses * households_number_of_old_houses) / (households_number_of_new_houses + households_number_of_old_houses)```

We put boundary conditions such that `insulation_fraction_new_houses` and `insulation_fraction_old_houses` have values on the interval [0,1].

Therefore, if we fill in the max. values the insulation fractions above can have in the `insulation_fraction_weighted_average`, we get:

``` insulation_fraction_weighted_average = (1* households_number_of_new_houses + 1 * households_number_of_old_houses) / (households_number_of_new_houses + households_number_of_old_houses)```

``` insulation_fraction_weighted_average = (households_number_of_new_houses + households_number_of_old_houses) / (households_number_of_new_houses + households_number_of_old_houses)```

Since the denominator and numerator are the same, we have

``` insulation_fraction_weighted_average = 1``` for the max. values of the individual insulation fractions.

**Comment by ChaelKruip** [comment]
> It seems to me that the max. value the insulation_fraction_weighted_average can have is 1.

You are 100% correct @RobTerwel I was not too sharp there! :+1:
